apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: "8.8.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    persistence:
      enabled: true
      storageClassName: proxmox-external-data
      size: 5Gi
    route:
      main:
        enabled: true
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        hostnames:
          - grafana.kubernetes.home
        parentRefs:
          - name: default-gateway
            namespace: gateway
