apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: mimir-distributed
      version: "5.7.0-weekly.327"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    alertmanager:
      enabled: false
    ingester:
      replicas: 1
      storageClass: proxmox-external-data
      zoneAwareReplication:
        enabled: false
    store_gateway:
      zoneAwareReplication:
        enabled: false
    # nginx:
    #   enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: "8.8.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    route:
      main:
        enabled: true
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        hostnames:
          - grafana.kubernetes.home
        parentRefs:
          - name: default-gateway
            namespace: gateway
