apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: mimir-distributed
      version: "5.7.0-weekly.327"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    alertmanager:
      enabled: false
