apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "73.2.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  values:
    alertmanager:
      enabled: false
    grafana:
      analytics:
        reporting_enabled: false
      persistence:
        enabled: true
        size: 5Gi
      additionalDataSources:
        - name: Loki
          access: proxy
          type: loki
          isDefault: false
          jsonData:
            httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: 1
          orgId: 1
          url: http://loki-gateway.loki.svc.cluster.local/
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
