apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "68.3.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  values:
    alertmanager:
      enabled: false
    grafana:
      defaultDashboardsTimezone: Europe/Amsterdam
      persistence:
        type: pvc
        enabled: true
        storageClassName: proxmox-external-data
        accessModes: ["ReadWriteOnce"]
        size: 20Gi
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: proxmox-external-data
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - grafana.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80