apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repos.yaml
  - kube-prometheus-stack.yaml
  - routes.yaml
  - pfsense-dashboards.yaml
  - cilium-dashboards.yaml