apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: mimir-distributed
      version: "5.7.0-weekly.327"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    alertmanager:
      enabled: false
    mimir:
      structuredConfig:
        multitenancy_enabled: false
    ingester:
      replicas: 1
      persistentVolume:
        storageClass: proxmox-external-data
      zoneAwareReplication:
        enabled: false
    store_gateway:
      persistentVolume:
        storageClass: proxmox-external-data
      zoneAwareReplication:
        enabled: false
    compactor:
      persistentVolume:
        storageClass: proxmox-external-data
    minio:
      enabled: true
    admin-cache:
      enabled: true
      replicas: 1
    chunks-cache:
      enabled: true
      replicas: 1
      allocatedMemory: 1024
    index-cache:
      enabled: true
      replicas: 1
      allocatedMemory: 1024
    metadata-cache:
      enabled: true
      allocatedMemory: 256
    results-cache:
      enabled: true
      replicas: 1
      allocatedMemory: 256
    # nginx:
    #   enabled: false
