apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      targetPort: http
      path: /metrics
    namespaceSelector:
      matchNames:
        - monitoring
    selector:
      matchLabels:
        app.kubernetes.io/name: kube-state-metrics