apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.25.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    grafana:
      enabled: true
    loki:
      enabled: false
    mimir:
      enabled: false
    tempo:
      enabled: false
    grafana-oncall:
      enabled: false