apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-distributed
  namespace: lgtm-distributed
spec:
  interval: 10m
  chart:
    spec:
      chart: lgtm-distributed
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    grafana:
      enabled: true
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Loki
              uid: loki
              type: loki
              url: http://{{ .Release.Name }}-loki-gateway
              isDefault: false
            - name: Mimir
              uid: prom
              type: prometheus
              url: http://{{ .Release.Name }}-mimir-nginx/prometheus
    loki:
      enabled: true
    mimir:
      enabled: true
    tempo:
      enabled: false
    grafana-oncall:
      enabled: false