apiVersion: ENC[AES256_GCM,data:ycg=,iv:Q6snrEtyyipPrSYB3SKQ2qXQUQN4mGMesZpehfY1rpY=,tag:9LRxaChUM58VwpTL9hDiLw==,type:str]
kind: ENC[AES256_GCM,data:4seQpJwe,iv:7NqEMz5gEYs4I/4wwgUdgr/wmVTGcAPXo7s/kHCZPOg=,tag:ut92r23O5TYDCwGOuorzYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5s8z4hBGWsZZ,iv:D1sQTL0H9ZpKSsKiE9c5JWnvQNKjeM3Ux6zKpdqgj4A=,tag:4f0m7gIzMTnitkn1BcwbFQ==,type:str]
    namespace: ENC[AES256_GCM,data:o01KuHZ9,iv:U8ZqFYoI1Y7nva2SOVgQmipTgLEi/uEBzBFV0iSQ0po=,tag:e6Er2ZS3rvoz0wSsN8UjUw==,type:str]
type: ENC[AES256_GCM,data:TsmznykW,iv:e/eNjYeCO90IIoABgfs6ptoLSJp8atP/q+smKChnfF4=,tag:kBgAOBEXhpEwC7Aaau115w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:DuePtjqA,iv:d2X6R4UMRX7ScKFlA+5AxEyR6dde/8dNWrJu176SWHs=,tag:4QfoMfdESDvlgXCdi2xPSQ==,type:str]
    password: ENC[AES256_GCM,data:X5YJepBu,iv:sjZc27AAQ7PHVlazDkZ+mSEWupuN28T4f+WGqWXPnog=,tag:henOfcn2rlZa049psXyWLg==,type:str]
    host: ENC[AES256_GCM,data:ID16QHR0WUaPS5yCNjJtKq94C7Bvt1gJXADl97Vc4WZV9av56A==,iv:2kTQp7IuBL1cqr72ojFRvYHRHnPGHCO0Vk3ykRoMO3M=,tag:nh/5RK8bsKmW36pElop8eA==,type:str]
    dbname: ENC[AES256_GCM,data:7foR2kKN,iv:HL5W7CbXmSsgKbv/JyJltxi75aD4x+tnm6MkK+1lC1o=,tag:JemI8zcY+ayQc52aQJ952g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEk3eDhGcHJi
            a2FjUWlZWllIamZpQmdRNE9ScDJyVng0SU40bko2SmRDdHN2MEFsNVZZRWpIc24v
            bmd0bUZ4TW1ndzI0aWdaMFA5UjkxSHhoWWZ5NXgybmFBMDJsQ2J5UWFJY2c1QUo0
            d3FuamZHT2tsL3ZQcnA4YUlxWXdUMUwzRzhKbThTVk1IeTZKbTlrV1ZqTzAzRVdy
            QlJxakwrbGFXdzM2UkFkUWQ2QUxsZ0daZ1VLdFl2ZDlrV3Q1SmFSOExjUHp4TDZo
            RjJCV2ExL1JYOVpTZWQ1UWhYeWxNTnIwa25zTC9La2crS1FQWlJjWVdhVVppbm96
            dDdHdFVjRS9RUytnNmNvUHc2N0dvREhsbjQrNmY3ZkI2b3hjQ2R3ZjN5d1Vxa1E4
            VEI1akRVY3d4Q1h4bnVVQTliZmpQcHdERUtydkIwQng5cWIyMllQaDd5Wjl0bHZj
            YWgrVWZiN2V1ZitxQTN6bEFleHk4cVdLUmxJMmtudzVUakJYSnJ4T0NpaHBxc2ox
            bnlEWW5SSHZvQkJibzNDeHFGc3pVMVpPVDJ0RTZ3WlBsV2tuUDdzZmdmQ0pSQ0FD
            ME9NY1dUc0pSTFM4eng3R0k4ejhLRVNEQkloWGVMVzN4ZjRJY0VzNDVWZjBJSlht
            bHNzdm5NY3VmcG9lUUhrV0pSMkFVY2NLWTBwWUxFRFNGQURvQUNSdzFoektrVEli
            M3dPV0MvUE1jL1ZFZWVOQ3BWQWoxOWxtbC9seDBFeVMwM2tzMDhhTUZ4NS8xaDFT
            cmVxb0JCZWNjNWxJS05uWXNHamxzQ2tXVW5lYzQ4dzBXWlljUCt3UVRVQ2UvSnk4
            TUhaaTdLd2g3MDRVcS9hKzlXOS91ODVMYWMrRUlwaDJPbS9sZ1NkalZxMjhIUCs1
            OHdDN0pyMUhDQnZ5bEF5WWMyUVNkNkU4bWlyNldaVk42cGRneXZHcGNnWU1EVUtB
            RktlWExCb25xWjFKNHVEZ200Q3l5Z29QRlhZeUM4UUN1KzZQbzNYQVlVTUNsTFdF
            cHZxckoxZGpnWkFoZWI4QVpPU1VnbkRtb0pvbGVZbkYrT1NrQXZMYjRTLzBWczEy
            VXhPTnJEUXluU1p0cmU4d0J3YUFMQ2IvR3o0djZBb0VTTmFzeWtRYkVVNnpiVVpD
            ZkQxNll6Y2pDalZJSHEvdm9wOElIWG8wN0VndU5zNUVEc2wxblY4U2FmS3g4WkZV
            M0prRjdITGJSSDRGNk5Ib1A2V3BnQnFzSlFaMWg2Q0YyY3hYUFN6enovMS9zclNK
            U3hKNUFlWFBvVUU4NmVUSG9NZWZZWUZHWDVuUlNUeVJmODVMbVFqaEZDcGI4VUUx
            aVNhZGtyWVVyZXVBYkdhckV5NjJQeHAvdit5dFNMM3lIbjZ5eVZuVy82cDRFL3pa
            dXhtZ3JMVDFTU3BWWThaV3V4bHh6WWJIV2pSOUFVbTVDaVhhanJaMDMwanhRSjJX
            QXd1RGg3YXZocGdZWTVzWmphUXNUVHBBSlMvRlRCcERXeHNpT2hPVEJqdi9qckxi
            MzV0YzVHcVhKS0F5cVFqUzlEaWhUcmFXZEdmSnFkaWhmOXNDS25RaTVSeXBjMms1
            alJoZzNBa0N6dUpTTWl2TjZsSWg5dnZLc1hid2FUMWordHliNGNRRVhCRGRCYW1V
            bDZhNkFNOXFaenF6eGNMd3ZZUTFKc2lIRERaemZhUURmMldPeGprYVhOM1VNaitp
            MFFoOWJUckFoYS9nY3lqSkJidFo2dmhNLzBaZkdHN2o4QlZYaGxVUjFHaFZNdXJl
            L1VUMjg5dWdoZjJkaXlSTnFLamk4YXNuV2NhblcvUDlMdDl6bDhySlU0Y2NwZU1D
            d2ZCQjFDajVTLzFGRW9HL2tiMzRFek5QaUVNY0VpNmh0VnNjM0VSelR6YUdaVXNm
            OWZrelZLL250a1psRE84a3RVaTd4Y0dlQ1UyS1ZZc3Fxb1RPY2E4ekRHQytTQQpX
            dWhrSUN1K29RUGwyS2syb0hmRkN5ME41WUhjNzNCcWhhVit3VGFpZVlBCi0tLSBQ
            b1d3SGpSSEQ0ZmJJMGNiRUNZQ1JaVVhzdlcrK1QvRWxHclVHM0x3NWhzCjROIINL
            tXwHHRpF8sUG3fPXU1l4+n6uRbVCQONYrAjfy1H6M9PUlceu7cekoRdpyDRFUpqE
            /zsJUi0MM3G/67E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq12jjf3cmmw26g585z9duxqc24ggj99djgzjcnznhy760a8eddgcy29a2cdu529wefxe75z4x83r288ueuvauysdq6tzmkmafysc6edkctqcz5j037qqp7xkml7mgc73z24vdztxwl8v048nq2zgvkwhljwnc4f2etzrywmdre7ed80v72gxfqrd35xs3k7g2mvu5876ecdhyg4ypqw9qtpud0f63uqs4y4nxpqsdyhgqqspz72jdxnwzv0ku8hpe98nx60skv58fq793h9zvwezncgpa7afjfyh2cx8wf2x0ckg3q56ay692eszvff9kudy2c493kke7gsst6yug4uxx5hgk503k5q3z8rz20j3wtykrf5a7y00w7agals7q6cp2qrvxqk7dvq8wwzr8mlyegf8epcran8uxpy434kxvaevyuef346hg9066xtf725gn2wqyxufz5j37ckgrry463ckay0g5hc6apzzm4w8rtc7evrg4e96q66tpy5c558fxawnksjqrs32qxuweehfrged5g22qvk4c997a0xakr0m7tc8fgrvxh8qnc9eq6g9stt5850zx2g7al757w2as8py2hq762eed3d977sjh657fzn4qp5trjswsgnypqmjvzutqqxkx8ngtjyhnkn9w3h2c0muq0ttzeyzfg90sgfgetgjcrgdacutc8s9c45ywwzuwl3xmslcy90k2chz8tdtheq92lj9kat4w8agjky78syjfqkd0rj5vr79fylw68q32f4a565a3x6xg8cer5lzcq64segegh89rn0yqv4p39jhv90szhz5d4qwfa3v03w3j0nt9fkjm2fsmpfzp7ydu5rvrzws9598mjp2kkrj2sydf92jmdlgqr9vjcwta5yw9dlxguy63h9w4qarcrcn92yy6puyzywdg7vv398dvpkqpsfj05djruua6p0cgv9cw5r6ac5h8lckml9a6gluyhd23yjf3tvt47q2pm3a4llc3c8uatpav5gwzumsjlvu3a6g4f07mchac4ddj0u729k72wzmzu5uvrfekmej4vvwyrmqv24yzvv6kfkyne582kczck5gzks5z2mvfxgae6p2dsqqc9cx4va4sucpsugnce4fc40fpghua9uw6yzgpz5ljmyg5sxtrpavyg9y3ed704vuv0tfay65ph0wqc07yntx2sngukvxz264lyjarcumk2z0628cvwqjqguyjsm3a6xnvnzptpj8tj8dnzdv9av5wd326geywfh74t2t3ts735psnlm52ucrpv4mzg5csfgyrkkzruhtsed2h93yvk08x9jfs5e0rm8f9uvvv8fqglkfxq9rp07lxqehn8hckp33h38gch7hz3mw943pdvceg5p75zjawjfzyxx44jqpg8tlrjgauuvfde2srt95sp7za5suxq5677jsxcrv08asedyxd3fdurt9h5sse2nq9xceyushuy8j058u4lpnvrzxlt0qx9rra4h5gz8mpj4jtr7apz8txgh23nndc98l7kvmffy2e63qn22s94j3vh06tnnzzekgc3m54r2ac3n0xrxlkwqgnpa9sa7xvdd539hgxsygkvkg4sycpdphyvxkc5zlc2tscxpqzjrdnt8rpwxhc2yfns3uxrk9ar9qtjnan4f3ch7v34gzzchtsndd4aay33dvg8qu0mhw5q29h53qmykpal7gzpmmz5qdk6kvlf5uwkxy5gf4v68az6t4ct5qd999eeya2vv8jp5nlcx0s5cqhygcn2593tlhxp448hqw2dezfewan3hdtslqac7zhgn253d9jnfska8g7ls6rm7hhylc88vdumu9d24ux2etc5lw98ynswh8n98wtwn3syas50qhhx2zvekxrlpde9kq6xwn426nhf6kgqdr6lywk2e60yyqtv9gmn
    lastmodified: "2026-05-13T11:02:54Z"
    mac: ENC[AES256_GCM,data:KRadBPJJNgKo0LrA8jzkmfGsD8SIRE9+dsaSrQqi5CNAbO+HclXcS3wLzFQR+xT8wytWL2qtTdExNZVErLBDOH2r1GgmAMbD79sZNMfsQ1PUnJ2wQCBUbDpmBxXydPJFSGqelveTQL8nDHBPH5xSwMI329GmsA67TCBFcdtn+OQ=,iv:IMmXHW3b/vAR79/Ax1Cx8oKTB7piLcOBV97M/N2Xwdk=,tag:d+mduIiqZ1hvgyzQzo+hYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:NGY=,iv:qtVTDAKv1NdrsDf7jPDOu3D1UsZfIQgVwW/PkMOUMn0=,tag:rFaOV6YEseGiqxyo309umw==,type:str]
kind: ENC[AES256_GCM,data:7ZuiISRe,iv:/ZD5Nj/PsPi4d/WgYvs04jE0H9LRb1ia+IFVjc8IYIY=,tag:byCyTeJzrOKYQCWmMKl2Uw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CEWR+6YfiiYZYg==,iv:eKEJqtaaaDNeFh9tOds3JlCbQQapuGEfWjfVfp+wajo=,tag:CLhN1tMCgsy+X2k/3z4VEQ==,type:str]
    namespace: ENC[AES256_GCM,data:0vu8I6z6,iv:Y8p4bafLzuU8M4h1Zk+0QWSOG1CgZodYYqH44HZ+I3c=,tag:QXVYNFxb1DXHeI/4o3VjKA==,type:str]
type: ENC[AES256_GCM,data:I96dsc39,iv:0Lq//tHoPmyt+W9AsSWpb7vF0acJ01krOvzr8IN9rh0=,tag:WaBtE3014Dxdat7qgLHylw==,type:str]
stringData:
    email: ENC[AES256_GCM,data:bS3J+/MBzi4fRDXo3g/+eYE=,iv:FWepJwzGu5Y/2L/aOMTGgGIwbhRDtyZ+tkUXlVwgREM=,tag:FDRfp8B4JfchFqbdoIxccg==,type:str]
    password: ENC[AES256_GCM,data:BojzkuQ=,iv:R+PitaqoRAFHmvuRkCYzyyB2I9EYFMx1zfGW9qbTT+4=,tag:WAjBcbnRoTQAkLuwrMr5yQ==,type:str]
    name: ENC[AES256_GCM,data:LUrajEY=,iv:s8E4fRslqvCxWu4HgSfAqIilEns6hlAHPky2gnxgBtE=,tag:NSpe9sYQYkAFM1l5kQmK0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEk3eDhGcHJi
            a2FjUWlZWllIamZpQmdRNE9ScDJyVng0SU40bko2SmRDdHN2MEFsNVZZRWpIc24v
            bmd0bUZ4TW1ndzI0aWdaMFA5UjkxSHhoWWZ5NXgybmFBMDJsQ2J5UWFJY2c1QUo0
            d3FuamZHT2tsL3ZQcnA4YUlxWXdUMUwzRzhKbThTVk1IeTZKbTlrV1ZqTzAzRVdy
            QlJxakwrbGFXdzM2UkFkUWQ2QUxsZ0daZ1VLdFl2ZDlrV3Q1SmFSOExjUHp4TDZo
            RjJCV2ExL1JYOVpTZWQ1UWhYeWxNTnIwa25zTC9La2crS1FQWlJjWVdhVVppbm96
            dDdHdFVjRS9RUytnNmNvUHc2N0dvREhsbjQrNmY3ZkI2b3hjQ2R3ZjN5d1Vxa1E4
            VEI1akRVY3d4Q1h4bnVVQTliZmpQcHdERUtydkIwQng5cWIyMllQaDd5Wjl0bHZj
            YWgrVWZiN2V1ZitxQTN6bEFleHk4cVdLUmxJMmtudzVUakJYSnJ4T0NpaHBxc2ox
            bnlEWW5SSHZvQkJibzNDeHFGc3pVMVpPVDJ0RTZ3WlBsV2tuUDdzZmdmQ0pSQ0FD
            ME9NY1dUc0pSTFM4eng3R0k4ejhLRVNEQkloWGVMVzN4ZjRJY0VzNDVWZjBJSlht
            bHNzdm5NY3VmcG9lUUhrV0pSMkFVY2NLWTBwWUxFRFNGQURvQUNSdzFoektrVEli
            M3dPV0MvUE1jL1ZFZWVOQ3BWQWoxOWxtbC9seDBFeVMwM2tzMDhhTUZ4NS8xaDFT
            cmVxb0JCZWNjNWxJS05uWXNHamxzQ2tXVW5lYzQ4dzBXWlljUCt3UVRVQ2UvSnk4
            TUhaaTdLd2g3MDRVcS9hKzlXOS91ODVMYWMrRUlwaDJPbS9sZ1NkalZxMjhIUCs1
            OHdDN0pyMUhDQnZ5bEF5WWMyUVNkNkU4bWlyNldaVk42cGRneXZHcGNnWU1EVUtB
            RktlWExCb25xWjFKNHVEZ200Q3l5Z29QRlhZeUM4UUN1KzZQbzNYQVlVTUNsTFdF
            cHZxckoxZGpnWkFoZWI4QVpPU1VnbkRtb0pvbGVZbkYrT1NrQXZMYjRTLzBWczEy
            VXhPTnJEUXluU1p0cmU4d0J3YUFMQ2IvR3o0djZBb0VTTmFzeWtRYkVVNnpiVVpD
            ZkQxNll6Y2pDalZJSHEvdm9wOElIWG8wN0VndU5zNUVEc2wxblY4U2FmS3g4WkZV
            M0prRjdITGJSSDRGNk5Ib1A2V3BnQnFzSlFaMWg2Q0YyY3hYUFN6enovMS9zclNK
            U3hKNUFlWFBvVUU4NmVUSG9NZWZZWUZHWDVuUlNUeVJmODVMbVFqaEZDcGI4VUUx
            aVNhZGtyWVVyZXVBYkdhckV5NjJQeHAvdit5dFNMM3lIbjZ5eVZuVy82cDRFL3pa
            dXhtZ3JMVDFTU3BWWThaV3V4bHh6WWJIV2pSOUFVbTVDaVhhanJaMDMwanhRSjJX
            QXd1RGg3YXZocGdZWTVzWmphUXNUVHBBSlMvRlRCcERXeHNpT2hPVEJqdi9qckxi
            MzV0YzVHcVhKS0F5cVFqUzlEaWhUcmFXZEdmSnFkaWhmOXNDS25RaTVSeXBjMms1
            alJoZzNBa0N6dUpTTWl2TjZsSWg5dnZLc1hid2FUMWordHliNGNRRVhCRGRCYW1V
            bDZhNkFNOXFaenF6eGNMd3ZZUTFKc2lIRERaemZhUURmMldPeGprYVhOM1VNaitp
            MFFoOWJUckFoYS9nY3lqSkJidFo2dmhNLzBaZkdHN2o4QlZYaGxVUjFHaFZNdXJl
            L1VUMjg5dWdoZjJkaXlSTnFLamk4YXNuV2NhblcvUDlMdDl6bDhySlU0Y2NwZU1D
            d2ZCQjFDajVTLzFGRW9HL2tiMzRFek5QaUVNY0VpNmh0VnNjM0VSelR6YUdaVXNm
            OWZrelZLL250a1psRE84a3RVaTd4Y0dlQ1UyS1ZZc3Fxb1RPY2E4ekRHQytTQQpX
            dWhrSUN1K29RUGwyS2syb0hmRkN5ME41WUhjNzNCcWhhVit3VGFpZVlBCi0tLSBQ
            b1d3SGpSSEQ0ZmJJMGNiRUNZQ1JaVVhzdlcrK1QvRWxHclVHM0x3NWhzCjROIINL
            tXwHHRpF8sUG3fPXU1l4+n6uRbVCQONYrAjfy1H6M9PUlceu7cekoRdpyDRFUpqE
            /zsJUi0MM3G/67E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq12jjf3cmmw26g585z9duxqc24ggj99djgzjcnznhy760a8eddgcy29a2cdu529wefxe75z4x83r288ueuvauysdq6tzmkmafysc6edkctqcz5j037qqp7xkml7mgc73z24vdztxwl8v048nq2zgvkwhljwnc4f2etzrywmdre7ed80v72gxfqrd35xs3k7g2mvu5876ecdhyg4ypqw9qtpud0f63uqs4y4nxpqsdyhgqqspz72jdxnwzv0ku8hpe98nx60skv58fq793h9zvwezncgpa7afjfyh2cx8wf2x0ckg3q56ay692eszvff9kudy2c493kke7gsst6yug4uxx5hgk503k5q3z8rz20j3wtykrf5a7y00w7agals7q6cp2qrvxqk7dvq8wwzr8mlyegf8epcran8uxpy434kxvaevyuef346hg9066xtf725gn2wqyxufz5j37ckgrry463ckay0g5hc6apzzm4w8rtc7evrg4e96q66tpy5c558fxawnksjqrs32qxuweehfrged5g22qvk4c997a0xakr0m7tc8fgrvxh8qnc9eq6g9stt5850zx2g7al757w2as8py2hq762eed3d977sjh657fzn4qp5trjswsgnypqmjvzutqqxkx8ngtjyhnkn9w3h2c0muq0ttzeyzfg90sgfgetgjcrgdacutc8s9c45ywwzuwl3xmslcy90k2chz8tdtheq92lj9kat4w8agjky78syjfqkd0rj5vr79fylw68q32f4a565a3x6xg8cer5lzcq64segegh89rn0yqv4p39jhv90szhz5d4qwfa3v03w3j0nt9fkjm2fsmpfzp7ydu5rvrzws9598mjp2kkrj2sydf92jmdlgqr9vjcwta5yw9dlxguy63h9w4qarcrcn92yy6puyzywdg7vv398dvpkqpsfj05djruua6p0cgv9cw5r6ac5h8lckml9a6gluyhd23yjf3tvt47q2pm3a4llc3c8uatpav5gwzumsjlvu3a6g4f07mchac4ddj0u729k72wzmzu5uvrfekmej4vvwyrmqv24yzvv6kfkyne582kczck5gzks5z2mvfxgae6p2dsqqc9cx4va4sucpsugnce4fc40fpghua9uw6yzgpz5ljmyg5sxtrpavyg9y3ed704vuv0tfay65ph0wqc07yntx2sngukvxz264lyjarcumk2z0628cvwqjqguyjsm3a6xnvnzptpj8tj8dnzdv9av5wd326geywfh74t2t3ts735psnlm52ucrpv4mzg5csfgyrkkzruhtsed2h93yvk08x9jfs5e0rm8f9uvvv8fqglkfxq9rp07lxqehn8hckp33h38gch7hz3mw943pdvceg5p75zjawjfzyxx44jqpg8tlrjgauuvfde2srt95sp7za5suxq5677jsxcrv08asedyxd3fdurt9h5sse2nq9xceyushuy8j058u4lpnvrzxlt0qx9rra4h5gz8mpj4jtr7apz8txgh23nndc98l7kvmffy2e63qn22s94j3vh06tnnzzekgc3m54r2ac3n0xrxlkwqgnpa9sa7xvdd539hgxsygkvkg4sycpdphyvxkc5zlc2tscxpqzjrdnt8rpwxhc2yfns3uxrk9ar9qtjnan4f3ch7v34gzzchtsndd4aay33dvg8qu0mhw5q29h53qmykpal7gzpmmz5qdk6kvlf5uwkxy5gf4v68az6t4ct5qd999eeya2vv8jp5nlcx0s5cqhygcn2593tlhxp448hqw2dezfewan3hdtslqac7zhgn253d9jnfska8g7ls6rm7hhylc88vdumu9d24ux2etc5lw98ynswh8n98wtwn3syas50qhhx2zvekxrlpde9kq6xwn426nhf6kgqdr6lywk2e60yyqtv9gmn
    lastmodified: "2026-05-13T11:02:54Z"
    mac: ENC[AES256_GCM,data:KRadBPJJNgKo0LrA8jzkmfGsD8SIRE9+dsaSrQqi5CNAbO+HclXcS3wLzFQR+xT8wytWL2qtTdExNZVErLBDOH2r1GgmAMbD79sZNMfsQ1PUnJ2wQCBUbDpmBxXydPJFSGqelveTQL8nDHBPH5xSwMI329GmsA67TCBFcdtn+OQ=,iv:IMmXHW3b/vAR79/Ax1Cx8oKTB7piLcOBV97M/N2Xwdk=,tag:d+mduIiqZ1hvgyzQzo+hYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
