apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retain
provisioner: nfs.csi.k8s.io
parameters:
  server: proxmox76.home
  share: /data/retain
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - noatime
  - async
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: proxmox76.home
  share: /data/delete
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - noatime
  - async
  - nodiratime
