apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: external-data-nextcloud
provisioner: nfs.csi.k8s.io
parameters:
  server: proxmox.home
  share: /external-data/nextcloud
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: external-data
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: proxmox.home
  share: /external-data/data
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1