apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-external-data-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: external_data
  cache: none
  ssd: "false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-external-data-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: external_data
  cache: none
  ssd: "false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
