apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: external-data-nfs-retain
provisioner: nfs.csi.k8s.io
parameters:
  server: proxmox.home
  share: /external-data/nextcloud
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: external-data-nfs-delete
provisioner: nfs.csi.k8s.io
parameters:
  server: proxmox.home
  share: /external-data/nextcloud
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1