apiVersion: ENC[AES256_GCM,data:Q2U=,iv:QhSQMP8hRLW87yzWPHwuZN1x+5DFyJj68P/hN2C5P2E=,tag:o6vKKqwkCyGc1xX+gMoksA==,type:str]
kind: ENC[AES256_GCM,data:AHfuj977,iv:L7EKOTELch1YcojL/wrHAgMjV7+uSQrT/EUGdl6VTNw=,tag:p3ueb2SztpCFPRiUs4P3oQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4jpVHRm4xXji07nnkL8yLNxDRU0oEVBkIg==,iv:gIf3mPqfu4e9MiWmqrpIJMUptdYyXLfv5QfwlTpTPgA=,tag:fcfv1zlxDB6n3zes6EpPmA==,type:str]
    namespace: ENC[AES256_GCM,data:io9k8db6ELtIUck=,iv:eGojAvsHrkj2urdxlaxrdvjXao6iByJScTE+Tzn9xRg=,tag:pzCl4dnS51dD06Wb1Gz1uQ==,type:str]
type: ENC[AES256_GCM,data:+6I0aqqO,iv:E2Nw0H5z9FoyeJcNxEkgGWkR8WoMB4mUUa2787tMDuU=,tag:m/It16iTj5EYFQ2ip3kmCg==,type:str]
stringData:
    host: ENC[AES256_GCM,data:G7ApiQcZIa2h7I30KQ==,iv:tq9StpBDRdiiAmkrALhYBzjHVE5oa/pqB/oVV9QtwQw=,tag:a3wnN3CJZRWQslt46NYpaw==,type:str]
    username: ENC[AES256_GCM,data:umawLT3S3LAiRq9Aodo=,iv:NCLFsdsZTNpMO4VS0sVjhNS28bi8/9bALkOYowfY7gs=,tag:HS7qu8qyGMTCt+x4zFXldA==,type:str]
    port: ENC[AES256_GCM,data:T/w=,iv:9IzNNJ+aXEMINM4d6ypaHGsx9Cn9SIZn05uSua2lepY=,tag:Ot/3N1QyAK0NcBluCYNzgg==,type:str]
    privateKey: ENC[AES256_GCM,data:wR2wagZpbXSTyogv+LClFlgwsyAq0SoazHc7ACjIcDZClafB27wYIh/lN4c2iDFTijDKKl3FIyOK+PoSJ9DC26Owgic2HTNpjyBMvlh16NoAuVrD1nSqSZhtMtFTkwTO0/CXLW2ZZ1PU01OuY+NMiCAIM1PueafssPbKEOcO/srhRAqrM/eOt0jRndv+bKOWJf86syFjHBieRWNugTyGXeprP4Mk/BQ4tN3WXbap3ukksxkVwYVBhjwpTJj79d7jFW0ndthzlmo8rQvXvLXaYLxR8o9PjMO9ihQd369b0A5/R6r9D3VjoHpiuP0jE5brOIh2uiakTgxzQq2787eUmxuE62neTPEH6D6MubN+37KZSmwYY0X6Kv0kJyvYGTOyw7ljcar0eCmLQXRK+L0j4lEsfeUtm+vk/decq6YRuXNE5dmZe+MpQ77tlEOH4RVD/8vCvPW9LgRaHo9LUneeexsa/bgx/7AeH6Ls7wyRqIstroKEehoThbue63RpoAmtKl+eRBADp3Y+kOcpgwqx+C2whKJqHhvzZywXAyyFXL7Fk6w=,iv:29WzOj4+HPpSBe+CFcnR7HZOY+UcGILAVaIF3Wk5PoQ=,tag:j/Ou6crw5Shx5NKMWDwqyw==,type:str]
    shareHost: ENC[AES256_GCM,data:CBbjvsyBCwU+giLGrw==,iv:aziBWnthsICApx5cwsia9bbPDiQeZKzCcxaCO+dhiCc=,tag:cukOugK7nUo6ekQVynMK+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV2VBbGUyTlRzM00vSGlD
            QUg3b1poWjAzckpIRnFTS0wrQXlBUTBobTBRCmxrWkxpRjJHV1Rrd0hpaTFLQjQ3
            OEE3QjF0MkNZaHp0MnJWQnRma245ejgKLS0tIG5YUlBkWXZweDR6TzFwOGFQaC9k
            alJHTXdVR005bURIMzBqcXlhZStIRFUKz3AD8g4JZ23tqtKuMB21hfqnnoJgF7rI
            6OFLkSZlThS5WbF14yaSNCUzsZLZIJFKW7tjb96zoqEJt/NGRUzURA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T12:03:32Z"
    mac: ENC[AES256_GCM,data:IuUbcgIOs/M8YQCBZB0iIA4FRpraOojdCVGDxXJgzKNXrJMnxBps7ZvB5mErhFSPJe5CVbapc9VmcA3HDlGAKsan50h54DYg2YTVXEqZHt4V7GKeWMRaw1R21EfjaP2Hyh8DE7tQJd4GexL4wglvWlXLRHKYUUseZGeLic/vYX8=,iv:/tu1rnQGYQYq5ZDz+haknvHIavSznqZuckjhT3JFTIs=,tag:bw6yXfdXmZE7QxA6mCjJUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
