apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cloudnative-pg
spec:
  instances: 1
  managed:
    - name: immich
      superuser: true
      login: true
  storage:
    storageClass: retain
    size: 1Gi
