apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 10m
  values:
    env:
      DB_PASSWORD:
        secretKeyRef:
          name: immich-db
          key: password
      DB_USERNAME:
        secretKeyRef:
          name: immich-db
          key: username
      DB_HOSTNAME:  "immich-db"
    immich:
      metrics:
        enabled: true
      persistence:
        existingClaim: immich-photos
