apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-minio
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: tenant
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 10m
  values:
    tenant:
      name: immich
      configSecret:
        name: env-config
        existingSecret: true
      pools:
        - name: immich
          servers: 1
          volumesPerServer: 1
          size: 100Gi
          storageClassName: retain
      buckets:
        - name: photos
      certificate:
        requestAutoCert: false
      metrics:
        enabled: true
