apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  resources:
    requests:
      storage: 50Gi