{
 "title": "pfsense/firewall",
 "tags": [ "pfsense" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Blocked Inbound Src IP",
   "type": "geomap",
   "gridPos": { "h": 28, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{__name=\"pfsensetail_ip_block_log\"} |= `duplicateeventstatus=\"+\"` |= `direction=\"in\"`"
    }
   ]
  },
  {
   "title": "Top Blocked IPs (by GeoIP)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(geoip_code) (count_over_time({__name=\"pfsensetail_ip_block_log\"} |= `duplicateeventstatus=\"+\"` |= `direction=\"in\"` [$__auto]))",
     "legendFormat": "{{geopip_code}}"
    }
   ]
  },
  {
   "title": "Top Blocked Domains by Feed",
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(feed_name) (count_over_time({__name=\"pfsensetail_ip_block_log\"} |= `duplicateeventstatus=\"+\"` [$__auto]))",
     "legendFormat": "{{feed_name}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{__name=\"pfsensetail_ip_block_log\"} |= `duplicateeventstatus=\"+\"` |= `direction=\"in\"`"
    }
   ]
  }
 ]
}