{
 "title": "pfsense/dnsbl",
 "tags": [ "pfsense" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dnsbl_src_ip",
    "query": {}
   },
   { "name": "filter", "label": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Blocked Domains",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(tld) (count_over_time({__name=\"pfsensetail_dnsbl_log\", src_ip=~\"$dnsbl_src_ip\"} |= `duplicateeventstatus=\"+\"` [$__auto]))",
     "legendFormat": "{{tld}}"
    }
   ]
  },
  {
   "title": "Blocked Domains by Src IP",
   "type": "status-history",
   "gridPos": { "h": 24, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(src_ip) (count_over_time({__name=\"pfsensetail_dnsbl_log\", src_ip=~\"$dnsbl_src_ip\"} |= `duplicateeventstatus=\"+\"` [$__auto]))",
     "legendFormat": "{{src_ip}}"
    }
   ]
  },
  {
   "title": "Total Blocked Domains by Src IP",
   "type": "stat",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(src_ip) (count_over_time({__name=\"pfsensetail_dnsbl_log\", src_ip=~\"$dnsbl_src_ip\"} |= `duplicateeventstatus=\"+\"` [$__auto]))",
     "legendFormat": "{{src_ip}}"
    }
   ]
  },
  {
   "title": "Top Blocked Domains by Feed",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(feed_name) (count_over_time({__name=\"pfsensetail_dnsbl_log\", src_ip=~\"$dnsbl_src_ip\"} |= `duplicateeventstatus=\"+\"` [$__auto]))",
     "legendFormat": "{{feed_name}}"
    }
   ]
  },
  {
   "title": "Top Blocked Domains by Blocklist",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(blocklist) (count_over_time({__name=\"pfsensetail_dnsbl_log\"} |= `duplicateeventstatus=\"+\"` [$__auto]))",
     "legendFormat": "{{feed_name}}"
    }
   ]
  }
 ]
}