apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  podTemplate:
    spec:
      securityContext:
        fsGroup: 1000
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1
  postgresUID: 1000
  postgresGID: 1000
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
  storage:
    storageClass: retain
    size: 1Gi
