apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 10m
  values:
    env:
      DB_PASSWORD:
        secretKeyRef:
          name: immich-db
          key: password
      DB_USERNAME:
        secretKeyRef:
          name: immich-db
          key: username
      DB_HOSTNAME: "immich-db-rw.immich.svc.cluster.local"
    immich:
      metrics:
        enabled: false # TODO: disabled metrics for now, since it relies on servicemonitor crds which are now not installed (was part of kube-prometheus-stack)
      persistence:
        library:
          existingClaim: immich-data
      configuration:
        newVersionCheck:
          enabled: false
        ffmpeg:
          acceptedVideoCodecs: [h264, hevc, vp9, av1]
    # TODO:
    valkey:
      enabled: true
