apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - cilium-network-policies.yaml
  - helm-repos.yaml
  - database.yaml
  - pvc.yaml
  - immich.yaml
  - routes.yaml

patches:
  - target:
      kind: HelmRelease
      name: immich
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: immich
