apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-todo
spec:
  description: allow imich machine learning to access huggingface.co and cas-bridge.xethub.hf.co
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: machine-learning
  egress:
    - toFQDNs:
        - matchName: huggingface.co
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toFQDNs:
        - matchName: cas-bridge.xethub.hf.co
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toFQDNs:
        - matchName: cas-server.xethub.hf.co
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toFQDNs:
        - matchName: transfer.xethub.hf.co
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toFQDNs:
        - matchName: modelscope.cn
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
