apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - helm-repos.yaml
  - metrics-server.yaml

patches:
  - target:
      kind: HelmRelease
      name: metrics-server
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: kube-system
