apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-metrics-server-to-nodes
spec:
  description: allow the metrics-server to scrape kubelet
  endpointSelector:
    matchLabels:
      "k8s:app.kubernetes.io/name": metrics-server
      "k8s:io.kubernetes.pod.namespace": kube-system
  ingress:
    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
  egress:
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
