apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: alloy
spec:
  interval: 10m
  chart:
    spec:
      chart: k8s-monitoring
      version: "3.0.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    cluster:
      name: talos
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-logs:
      enabled: false
    alloy-receiver:
      enabled: false
    destinations:
      - name: loki
        type: loki
        url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      - name: mimir
        type: prometheus
        url: http://mimir-nginx.mimir.svc.cluster.local/api/v1/push
    annotationAutodiscovery:
      enabled: true
    clusterEvents:
      enabled: true
      collector: alloy-singleton
    clusterMetrics:
      enabled: true
      collector: alloy-metrics
    nodeLogs:
      enabled: false
    podLogs:
      enabled: true
      collector: alloy-singleton
      structuredMetadata:
        pod: pod
      labelsToKeep:
        - app
        - app_kubernetes_io_name
        - component
        - container
        - job
        - level
        - namespace
        - pod
        - service_name
      gatherMethod: kubernetesApi
