apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: default-gateway
      hostname: "*.kubernetes.home" 
      allowedRoutes:
        namespaces:
          from: All