apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: influxdb2
      version: "2.1.2"
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: flux-system
      interval: 10m
