apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: influxdb2
      version: "2.1.2"
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: flux-system
      interval: 10m
  values:
    persistence:
      enabled: true
      storageClass: proxmox-external-data
      accessMode: ReadWriteOnce
      size: 20Gi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: influxdb-pfsense
  namespace: monitoring
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  rules:
    - matches:
        - path:
            value: /api/v2/write
        - queryParams:
            - type: Exact
              name: bucket
              value: pfsense
            - type: Exact
              name: org
              value: influxdata
      backendRefs:
        - name: influxdb-influxdb2
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: influxdb
  namespace: monitoring
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - influxdb.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: influxdb-influxdb2
          port: 80