apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-state-metrics
      version: "5.28.0"
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: flux-system
      interval: 10m
