apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: "6.6.3"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 10m
  values:
    nextcloud:
      host: nextcloud.kubernetes.home
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-postgresql
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: database
    # postgres:
    #   enabled: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - nextcloud.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nextcloud
          port: 8080