apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-external-data
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: external_data
  cache: none
  ssd: "false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer