apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: "9.2.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    grafana.ini:
      analytics:
        check_for_updates: false
    persistence:
      enabled: true
      size: 5Gi
    admin:
      existingSecret: grafana-admin
      userKey: admin-user
      passwordKey: admin-password
    sidecar:
      dashboards:
        enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            access: proxy
            type: loki
            isDefault: false
            url: http://loki-gateway.loki.svc.cluster.local/
            orgId: 1
            jsonData:
              httpHeaderName1: X-Scope-OrgID
            secureJsonData:
              httpHeaderValue1: 1
          - name: Mimir
            access: proxy
            type: prometheus
            isDefault: true
            url: http://mimir-nginx.mimir.svc.cluster.local/prometheus
  