apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coroot-operator
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: coroot-operator
      version: "0.4.7"
      sourceRef:
        kind: HelmRepository
        name: coroot
      interval: 10m
