apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics-operator
resources:
  - namespace.yaml
  - helm-repos.yaml
  - victoria-metrics-operator.yaml

patches:
  - target:
      kind: HelmRelease
      name: victoria-metrics-operator
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: victoria-metrics-operator
