apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/democratic-csi

patches:
  - target:
      kind: HelmRelease
      name: democratic-csi
    patch: |-
      - op: add
        path: "/spec/values/driver/config/nfs/shareStrategySetDatasetProperties"
        value:
          properties:
            sharenfs: "-network 192.168.122.10/24 -mapall=65534:65534"
  - target:
      kind: CiliumNetworkPolicy
      name: allow-democratic-csi
    patch: |-
      - op: replace
        path: "/spec/egress/0/toCIDR/0"
        value: "192.168.122.10/32"
      - op: replace
        path: "/spec/egress/1/toFQDNs/0/matchName"
        value: "freebsd"
