apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/democratic-csi

patches:
  - target:
      kind: HelmRelease
      name: democratic-csi
    patch: |-
      - op: replace
        path: "/spec/values/driver/config/nfs/shareStrategySetDatasetProperties/properties/sharenfs"
        value: "-mapall=65534:65534 -network 192.168.122.10/24"
