apiVersion: ENC[AES256_GCM,data:+lM=,iv:Cr0edqMBVvxRc7nKFacRRBdLS3b8Ndn9tU5MeKDFW1k=,tag:qCKiytnHAmnhKFrcxc1i3A==,type:str]
kind: ENC[AES256_GCM,data:yfFYODG3,iv:FAorbWPaUt8KthrWR3NK1pI47jBkk06k9LIGzJ+uWMo=,tag:LFPkErlkrLoeUgTD8GQR6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ycmL4DgVsuFbfTI/l/dRVZ1SuMOD4KiQgA==,iv:HUjl5WNVsFwIu6ZKcY31YARqLZgg5ANXzxBAu2mzK8I=,tag:NTpFaZSE1AS2LTN9VWC5Sw==,type:str]
    namespace: ENC[AES256_GCM,data:w4DufYm3/g+6l34=,iv:YdqAfVEv70rb7+Yn1cU8srLVhq9wydk8GJHwuemGtmk=,tag:1TLhVVvkDImpbhy958PmcA==,type:str]
type: ENC[AES256_GCM,data:OkfQ2Vom,iv:vh9sHG2Miza55kH662EaNu/AG1Gtcrm0LKM3d/6Cyvo=,tag:EV9d7yUxumKRTqjQIvz4ow==,type:str]
stringData:
    host: ENC[AES256_GCM,data:pKauhZnL35dSQpI=,iv:9GJ17UvcedGVprtNjOj5Ygc+QWVv2P9fArqXiQ/gliA=,tag:HSAjb+ddRuUgbR7sLa2p8Q==,type:str]
    username: ENC[AES256_GCM,data:mBCupH8vgK/v3UOcZn4=,iv:MfIT6Mm53QPKrzyRdLYd4RlYp66g0RaJQHngSxCnCBU=,tag:nVz3nFV08vnMGPomM2ZKCQ==,type:str]
    port: ENC[AES256_GCM,data:OWE=,iv:wrnALvLkTePE6F1hFFf86zFliQXD2AzeeAMWMQqXAlw=,tag:OOvqaEZJuorWos3R3m+Qfg==,type:str]
    privateKey: ENC[AES256_GCM,data:/UtJjztMEaNSpN5WA9jr/gr3xE79LJRNPR9SyfNHV0JDEQCpjOpvPWzgWlItLAh+b46pVo9MrKFBhFglB0XcB76jiqXyg8beq3FXrpY2KcTcPAgNOcYnk7DAEZ7n6vKWH7ZJrwMFllrGEIFpkJehIgcGma9YGol0iPbIQkM2YeThb7GhzIiyJbTqq6PXaqYMceL+rzCJt1+6xG7ujs2hVNW/W10JOK5YEkYKfYu5G4D7K04UOx1A43JV7NV0PEUVXpTgWL7SpPr3Dp+FKxqUPX4ElDmqQhFdglVMqjsqhdUqESZwHGpC+laYCzRwxImjwRtLmuIykOKxbFZ9FSXWs602kCTTkcJPD/kuXMo0T7sBNpDTHQyI7FII+Yl2y9pb4tv1nPZqu8vfYsR9/tjTq6ZRFYTjWsTJjYkslM64P+x99qOKB6ABVzTPGqBXeRYK9FW64HHDBz9RLf9wJa0VXdEuHLpeAcJpeDf22xdnInr0q6kTUlR18Ns8eGK/HJgRbQMR9bUmtd5KUFTaO4GnPYCKZvOhHRNwDzMQ0SWIHrJ2J51Woqvrw25D8qOkWY9w,iv:xwiIhR3xFF77H/2uhxklPTHxiEszuIHg22zx51u7RtA=,tag:1nGxO8VuGwGtZydCwt5kfg==,type:str]
    shareHost: ENC[AES256_GCM,data:jSxV2Mr/qwZdlcs=,iv:+Zha18lWHEAxgDxz/Ux1DpcXqLF5ghSrHOrA0cE4ZFQ=,tag:n8h+kh10haXpzRg3FsZnJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdU9qV2xlcGR6WHIyMlNB
            NnpacXZreW9YMklHaUFZd3E3a1FTMHIveTJrCmdXR2ZVUG1nNzVFN1VtcG0wb0lX
            RFlpUDdMY1E1a1NuNGxCWFVacXZPVmsKLS0tIDJxL0txNm5FdW12amZ5cExCdDZN
            OVdYdGluZzkrMWdqOER1dTJMRnEwa0kKP9wPxrdUGdbV9nUlO35Mc8g1+BZcglmZ
            F8GdnpFqMaBn9/0M5+Qbzya298RMb61AL1EoVXtLf3gsS08ds45VKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-08-26T19:24:55Z"
    mac: ENC[AES256_GCM,data:VIgE/JUxNses9DkQ8PEBtBX9z7vDGAUF3rJbvdTmoHdaaNudnDj1H+WCr3fYxpUuPd1h9aST/3hDq+LAM6b712EAaSHfAuU6Vw7tLJfdAOakcvL6jXXBOrVDFDzLwfVvOZI8fbddH57vyzzS3aeGKiurRlz5crwf8VnW1W5TXDg=,iv:B8Qw5Qy6zrp8+Ood79IMTs6+G/jrdD/h5Pgh6Z7zjUc=,tag:VroshILK8KuXTfIzuo6Qlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
