apiVersion: ENC[AES256_GCM,data:+lM=,iv:Cr0edqMBVvxRc7nKFacRRBdLS3b8Ndn9tU5MeKDFW1k=,tag:qCKiytnHAmnhKFrcxc1i3A==,type:str]
kind: ENC[AES256_GCM,data:yfFYODG3,iv:FAorbWPaUt8KthrWR3NK1pI47jBkk06k9LIGzJ+uWMo=,tag:LFPkErlkrLoeUgTD8GQR6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ycmL4DgVsuFbfTI/l/dRVZ1SuMOD4KiQgA==,iv:HUjl5WNVsFwIu6ZKcY31YARqLZgg5ANXzxBAu2mzK8I=,tag:NTpFaZSE1AS2LTN9VWC5Sw==,type:str]
    namespace: ENC[AES256_GCM,data:w4DufYm3/g+6l34=,iv:YdqAfVEv70rb7+Yn1cU8srLVhq9wydk8GJHwuemGtmk=,tag:1TLhVVvkDImpbhy958PmcA==,type:str]
type: ENC[AES256_GCM,data:OkfQ2Vom,iv:vh9sHG2Miza55kH662EaNu/AG1Gtcrm0LKM3d/6Cyvo=,tag:EV9d7yUxumKRTqjQIvz4ow==,type:str]
stringData:
    host: ENC[AES256_GCM,data:+65lwJ8ko2u5ztVQ9tg=,iv:FI5ngtejRyd8qy4YvyQLwkjpcXzhoHboVcJFXKXm69s=,tag:yyMNcJhLlVhPB3vLKfmFkg==,type:str]
    username: ENC[AES256_GCM,data:mBCupH8vgK/v3UOcZn4=,iv:MfIT6Mm53QPKrzyRdLYd4RlYp66g0RaJQHngSxCnCBU=,tag:nVz3nFV08vnMGPomM2ZKCQ==,type:str]
    port: ENC[AES256_GCM,data:OWE=,iv:wrnALvLkTePE6F1hFFf86zFliQXD2AzeeAMWMQqXAlw=,tag:OOvqaEZJuorWos3R3m+Qfg==,type:str]
    privateKey: ENC[AES256_GCM,data:a/vN0+SKheYyIvdQ8TbVjbXbSPFnY/KrpsiGDEMMiuAggHAgfQnqMRj+z//5Fr1NpMI4TjSZdZM4/BZrtpvHQRDNVJsmN1sy9L+ZvYon1UdlJg8hNImp3M83LW0RMKAgIu/LmbaPhjQDZLcO8FjkG4h1hcFctmVle8UyTOhsgGjaRiMp3k4JoyvF1Ef2FovsOgeU16sydS/M8Mgz1aHfM7EAgLDF64U143TNsvKOit/u85r6ToPpxitZnZqRlnLmO7kw9lt312kGQIK0mCLEMA/Wycqh0Zfmb6toUbG6wX4AbCv2ZPUrdlESs5yPO3DU3V1143nTIhuY0PAyDVZVYupk9Ri16YIJdvFohAtMn5J6XdFtFl2RtpsylTT2dd4qOUBvGiBEuqCIK0+e/ThxSrTJa0KxDmKVzFuLr+EyhI/UTBSHUOB/X1w5asOGCK4iRkCEsPipXKQVUXKXCAUGHDj94a+UYBpS8aYWwBymwvfygPeiZYRJSYZgkNN879LkBHZl+HRnAbDllA489RJhZMxRgBDYRJKW867J2fCW/CdylEqKJSLaqrqiOXB8LwkY,iv:CssqYE1Bj61tSgPdhx64MLKpkIplxQhd6tFpSmvSNzY=,tag:AhK+qlj66Y2oiSTOVL3e0A==,type:str]
    shareHost: ENC[AES256_GCM,data:VGqoxB+/e5iicFeIf7g=,iv:n6jFTP66WWwzfB1em3jeECx8Yvg19cXcHStKkKqxt40=,tag:1rKK7CtmmG+WV+Wmm86zXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdU9qV2xlcGR6WHIyMlNB
            NnpacXZreW9YMklHaUFZd3E3a1FTMHIveTJrCmdXR2ZVUG1nNzVFN1VtcG0wb0lX
            RFlpUDdMY1E1a1NuNGxCWFVacXZPVmsKLS0tIDJxL0txNm5FdW12amZ5cExCdDZN
            OVdYdGluZzkrMWdqOER1dTJMRnEwa0kKP9wPxrdUGdbV9nUlO35Mc8g1+BZcglmZ
            F8GdnpFqMaBn9/0M5+Qbzya298RMb61AL1EoVXtLf3gsS08ds45VKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T12:02:26Z"
    mac: ENC[AES256_GCM,data:wWeSTLkrN51djL4TzHhC6bamtjnrb+NPNNy2c/5Pjoxh5P2QwtcOXobuH4w+KKEaBtjG2PEqndUbx3mNAP4lfyhIVjFMbC4McDEpmgkEQuzlP3UEjKSZL/vw6b3hGDI7CTkRsSLzUbxbyglgi44H81qlpwQtjIDEAd6fNQn4hBw=,iv:V6g5fj8rOsnAoTElLpZYMUmTmBKkSEWO9vUGUsYkjzY=,tag:9b80ZEIG/cvNA06ZF6L7Bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
