apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helm-repos.yaml
  - kube-prometheus-stack.yaml
  - routes.yaml
  - pfsense-dashboards.yaml
  - cilium-dashboards.yaml
  - hubble-dashboards.yaml

patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: monitoring
