apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: mimir
spec:
  interval: 10m
  chart:
    spec:
      chart: mimir-distributed
      version: "5.7.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: mimir-minio
    alertmanager:
      enabled: false
    ingester:
      persistentVolume:
        size: 1Gi
      replicas: 2
      zoneAwareReplication:
        enabled: false
    minio:
      enabled: false
    querier:
      replicas: 1
    store_gateway:
      zoneAwareReplication:
        enabled: false
    metaMonitoring:
      serviceMonitor:
        enabled: true
      grafanaAgent:
        enabled: true
        installOperator: true
        metrics:
          additionalRemoteWriteConfigs:
            - url: http://mimir-nginx.mimir.svc.cluster.local/api/v1/push
    mimir:
      structuredConfig:
        blocks_storage:
          backend: s3
          s3:
            endpoint: ${endpoint}
            bucket_name: mimir-tsdb
            access_key_id: ${accessKeyId}
            secret_access_key: ${secretAccessKey}
            insecure: true
        ruler_storage:
          backend: s3
          s3:
            endpoint: ${endpoint}
            bucket_name: mimir-ruler
            access_key_id: ${accessKeyId}
            secret_access_key: ${secretAccessKey}
            insecure: true
