apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: "6.6.3"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 10m
  values:
    persistence:
      enabled: true
      storageClass: proxmox-external-data-retain
      size: 100Gi
    nextcloud:
      host: nextcloud.kubernetes.home
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: username
        passwordKey: password
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      existingSecret:
        enabled: true
        secretName: nextcloud-mariadb
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: database
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: proxmox-external-data-retain
          size: 100Gi
      auth:
        existingSecret: nextcloud-mariadb
    phpClientHttpsFix:
      enabled: true
      protocol: https
    metrics:
      enabled: true
      info:
        apps: true
      service:
        annotations:
          k8s.grafana.com/scrape: true
          k8s.grafana.com/job: nextcloud
          k8s.grafana.com/instance: talos
          k8s.grafana.com/metrics.path: /metrics
          k8s.grafana.com/metrics.portName: metrics
          k8s.grafana.com/metrics.scheme: http
          k8s.grafana.com/metrics.scrapeInterval: 60s