apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: nextcloud
      version: "7.0.0"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 10m
  values:
    readinessProbe:
      initialDelaySeconds: 900
    livenessProbe:
      initialDelaySeconds: 900
    persistence:
      enabled: true
      storageClass: retain
      size: 10Gi
    nextcloud:
      podSecurityContext:
        fsGroupChangePolicy: "OnRootMismatch"
      host: nextcloud.kubernetes.home
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: username
        passwordKey: password
      objectStore:
        s3:
          enabled: true
          existingSecret: nextcloud-minio
          ssl: false
          port: 80
          usePathStyle: true
          secretKeys:
            host: endpoint
            accessKey: accessKeyId
            secretKey: secretAccessKey
            bucket: bucketname
    internalDatabase:
      enabled: true #false
    # externalDatabase:
    #   enabled: true
    #   type: mysql
    #   existingSecret:
    #     enabled: true
    #     secretName: nextcloud-mariadb
    #     usernameKey: username
    #     passwordKey: password
    #     hostKey: host
    #     databaseKey: database
    # mariadb:
    #   enabled: true
    #   primary:
    #     persistence:
    #       enabled: true
    #       storageClass: retain
    #       size: 10Gi
    #   auth:
    #     existingSecret: nextcloud-mariadb
    phpClientHttpsFix:
      enabled: true
      protocol: https
    metrics:
      enabled: true
      info:
        apps: true
      serviceMonitor:
        enabled: true
        namespace: nextcloud
        jobLabel: app.kubernetes.io/name