apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: "6.6.4"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 10m
  values:
    persistence:
      enabled: true
      storageClass: external-data-nextcloud
      size: 100Gi
    nextcloud:
      host: nextcloud.kubernetes.home
      containerPort: 8080
      securityContext:
        - CAP_NET_BIND_SERVICE
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: username
        passwordKey: password
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      existingSecret:
        enabled: true
        secretName: nextcloud-mariadb
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: database
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: external-data-nextcloud
          size: 100Gi
      auth:
        existingSecret: nextcloud-mariadb
    phpClientHttpsFix:
      enabled: true
      protocol: https
    metrics:
      enabled: true
      info:
        apps: true
      serviceMonitor:
        enabled: true
        namespace: nextcloud
        jobLabel: app.kubernetes.io/name
