apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/immich
  - secrets.yaml

patches:
  - target:
      kind: HTTPRoute
      name: immich
    patch: |-
      - op: add
        path: "/spec/hostnames"
        value:
          - immich.kubernetes.home
