apiVersion: ENC[AES256_GCM,data:zIo=,iv:jObZsqKaVrx2xrQPm6HRK589qV0onSxiquzeqJcTWUk=,tag:yaEcia2+wf+FnUPTY4O+xw==,type:str]
kind: ENC[AES256_GCM,data:woyEhMWs,iv:MUYcpbvA0YKT5wWYXMGq5gnCWakgvCvKWgyS5EJ2D0A=,tag:K3jK9akGkAdGhTJb7HUi5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9yKP22VOOO/r,iv:wdRM3ubsrW9t3Re7DZ4yKrSO+WWEo5X5BSvfkyGoGAc=,tag:3bMx+sPP+GlAwy+/YSSXzg==,type:str]
    namespace: ENC[AES256_GCM,data:F3m68K42,iv:9ztRZRgAbMCyS039pc9sQnCzzxqgjG1+AYX8SQlcCLU=,tag:QnLoqR6zshQ9+L7Czb0UVQ==,type:str]
type: ENC[AES256_GCM,data:tQH3RU9G,iv:GSQGlkNgvm/IPZRWi4u7q1WCna2H86ssoc6toRgZhZA=,tag:hrWtlKu98a4VPTS5ZfElrQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:bGkW+FHq,iv:biE6AtacLgkgRV9SzlLtEuM830djctzhg16hm0PxkVs=,tag:gPvyJdbK10YBfZOprENMnA==,type:str]
    password: ENC[AES256_GCM,data:EsrI8X7r,iv:sHiugl2ylDFxkcBwjR9FgbWDA2h6OGEZQRGUeB/fBK0=,tag:ijl48RyIrYgPqDWv56S+BQ==,type:str]
    host: ENC[AES256_GCM,data:pu8GrcT9xSoQCBId4tlGd+PqnJ2kUE6xK9ebP1sVqkCiBxnkfg==,iv:PfSXolon58uGfNKzBNvd6b/S6s62fgojxpb2YmH991E=,tag:nTVYZMzHwy98+KW8QLuoNQ==,type:str]
    dbname: ENC[AES256_GCM,data:YdGF/nzV,iv:zCNsORSTk1ydAFl73N8tir6i83ilv5+iYUfQN3hAg/U=,tag:yVOV2O/mQKcMAgaGmyOM3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb05HUiswcEF3Mm1UbDZr
            WDg5bk9tU0ZGZHBBN2R0cjZkS2dsaHNPZGtjCjEwWjJ1RzJjOXh0SGxUa09kVERw
            dnhCbHFBTTNGUjR1UkxzUjBkNWZKWTAKLS0tIFNRbTFzcUJIUXFiZEdlc2FwVWhP
            ajAveGZ0bHhEMkdzdVVZZFBaZ3l2TVEKByKFLeNR8reTNii7vNiWjXe4e5LuTGIE
            UX5DUXXJN/CQM2dqFbVjMsOKearxv7qxESqPPh8+jYKQT9Sl1yDInQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:47:46Z"
    mac: ENC[AES256_GCM,data:mpbOMjjma/8npwZTpDS3lRCMpaSLE5ftekWz7ZMNCiLyf55c4StZ65FSadnSBuWXfNR3tD4vfDnB8hKvSD40QiUO3p4iX/mvzQhjnBiW8oXoTHMfjWHQd4qu0PZRrVmVMXy0XGCuxeEV1Vsct6ZQx4NdoNkI7ck5F09Au7kpCcI=,iv:l50MNwpSDeZtSbBbvyhS5PS5umX8Fx+H6o84EDT4q1c=,tag:gAhMY8YBBWkn/r1oKQagNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:7HY=,iv:x79e69lT15tKMHqOxFjaM+RJS+FPMiTU15dmE4Xr03M=,tag:Ivy5LixJkvpOYp552q1sWQ==,type:str]
kind: ENC[AES256_GCM,data:HXclgmgW,iv:WHPnDIQUBRjDD4FEF6yTxffsh/Z7XHbxT4RUQXqqB+U=,tag:h1hsM0bKqYJg4xV3JRThow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B1lhcof0JiBXfA==,iv:N0glgX5ROVsYPrgMK/9mmW53ZgYRyjopdU5m/jyZNjc=,tag:u3tFmCk6l418eekvcf/L6w==,type:str]
    namespace: ENC[AES256_GCM,data:HtrkaL6W,iv:cnVn0n9HVmmXwr/uhvJFAwPgWJ1Y5GSGmegM1Fxa8FY=,tag:iQ5PF4hQ87tEcEbmbhZ6vQ==,type:str]
type: ENC[AES256_GCM,data:VFV6bEee,iv:I6Al1t2AHJm+bI6+qjCxTVsRAcbQ1hg1XsaL4JPWrXw=,tag:zBJlixD2OybRMQy3CdtIbw==,type:str]
stringData:
    email: ENC[AES256_GCM,data:m6WZBPy7dP38n+ngEDepVgY=,iv:6nK55gSjgCLG4sLeMvhZmNxnBnJunFjOf+dhxMeWTqE=,tag:oTmC+P1fLcdvWWeAPweInQ==,type:str]
    password: ENC[AES256_GCM,data:ep5hNM4=,iv:70yXy0Tvm+ZOBqgL5AcbJdlYgW2/ZHUG+M1MQ0advRc=,tag:rfeUs5mz64WS+okhrMdqUQ==,type:str]
    name: ENC[AES256_GCM,data:zqSI8xw=,iv:vuxl9PBlSM/zlGFyngFeReEO9DWpVXxWwF8DfT8mTqA=,tag:UtwrGus2j/6uztLGxgc44Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb05HUiswcEF3Mm1UbDZr
            WDg5bk9tU0ZGZHBBN2R0cjZkS2dsaHNPZGtjCjEwWjJ1RzJjOXh0SGxUa09kVERw
            dnhCbHFBTTNGUjR1UkxzUjBkNWZKWTAKLS0tIFNRbTFzcUJIUXFiZEdlc2FwVWhP
            ajAveGZ0bHhEMkdzdVVZZFBaZ3l2TVEKByKFLeNR8reTNii7vNiWjXe4e5LuTGIE
            UX5DUXXJN/CQM2dqFbVjMsOKearxv7qxESqPPh8+jYKQT9Sl1yDInQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:47:46Z"
    mac: ENC[AES256_GCM,data:mpbOMjjma/8npwZTpDS3lRCMpaSLE5ftekWz7ZMNCiLyf55c4StZ65FSadnSBuWXfNR3tD4vfDnB8hKvSD40QiUO3p4iX/mvzQhjnBiW8oXoTHMfjWHQd4qu0PZRrVmVMXy0XGCuxeEV1Vsct6ZQx4NdoNkI7ck5F09Au7kpCcI=,iv:l50MNwpSDeZtSbBbvyhS5PS5umX8Fx+H6o84EDT4q1c=,tag:gAhMY8YBBWkn/r1oKQagNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:GV4=,iv:XyCMRWVj2j3sOdFWVNGzf5jz7j1V8m+WTssbCU0Msu4=,tag:d0GvonDfjvgrl+3tgmYh7w==,type:str]
kind: ENC[AES256_GCM,data:gKl+4r0i,iv:FZ5lbifrCuvV532FjuR9xZ130svXC2qHcdD/dWRnsSo=,tag:QgWFR5eNG7iukd7Z/ZIjPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H0IXx5jYu7zXKmI=,iv:3bDTsWWt+YrSzUVSPQcnEc7US8UBdu6wTu4bLYtwZp8=,tag:E9gcXzjn4KcxQwjFsL3jlA==,type:str]
    namespace: ENC[AES256_GCM,data:SAqjV8eX,iv:IzzJIwbu3hP5SB1KV0XJbuCcolT+eldi935h4dFP05U=,tag:yvGBQGGFNFv+nS9ENZJUVQ==,type:str]
type: ENC[AES256_GCM,data:31LtwAp1,iv:MV5kAlq21SVNNlG1gm8gqbF6ZfTeuR4C/TjQSgcx2oE=,tag:d3xxfkpgyT+2SdIzwOhEag==,type:str]
stringData:
    email: ENC[AES256_GCM,data:oZ06UTSWWhRm39jPVzvxrElW,iv:Z45KxGKN+ZyE9EBoZ9rRc5W6zE7OAr+uYcJNq6clo1w=,tag:QKesFbbrpqJG5X+c3zv5nw==,type:str]
    password: ENC[AES256_GCM,data:y9T0W2Q7,iv:z0WBuNiK3DXbO9MAAfoGyU7S+KEpVUNvgdvufbNyVPk=,tag:lW49DCKfGcUb54y54TiwGQ==,type:str]
    name: ENC[AES256_GCM,data:6iwLRuor,iv:2f8CgHcK/51En6DzTnOOftWXH4r69I2YXmi5i5Ma9w8=,tag:5DWByX/y9AOo+GyjbU1OPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb05HUiswcEF3Mm1UbDZr
            WDg5bk9tU0ZGZHBBN2R0cjZkS2dsaHNPZGtjCjEwWjJ1RzJjOXh0SGxUa09kVERw
            dnhCbHFBTTNGUjR1UkxzUjBkNWZKWTAKLS0tIFNRbTFzcUJIUXFiZEdlc2FwVWhP
            ajAveGZ0bHhEMkdzdVVZZFBaZ3l2TVEKByKFLeNR8reTNii7vNiWjXe4e5LuTGIE
            UX5DUXXJN/CQM2dqFbVjMsOKearxv7qxESqPPh8+jYKQT9Sl1yDInQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:47:46Z"
    mac: ENC[AES256_GCM,data:mpbOMjjma/8npwZTpDS3lRCMpaSLE5ftekWz7ZMNCiLyf55c4StZ65FSadnSBuWXfNR3tD4vfDnB8hKvSD40QiUO3p4iX/mvzQhjnBiW8oXoTHMfjWHQd4qu0PZRrVmVMXy0XGCuxeEV1Vsct6ZQx4NdoNkI7ck5F09Au7kpCcI=,iv:l50MNwpSDeZtSbBbvyhS5PS5umX8Fx+H6o84EDT4q1c=,tag:gAhMY8YBBWkn/r1oKQagNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:t/8=,iv:9nMSoLQACMtPCJnqr3UsLYd1iZclS4Wt+nKqwmb70wo=,tag:f7j33M7XoFCvylkgtgKf8g==,type:str]
kind: ENC[AES256_GCM,data:/0QpQ+WR,iv:lQDAUL/qYblk98MA3Qv7Z0D16DHvGIDSA4llbpN+wQA=,tag:h35ERC+FlccsFzxWKCZAVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oLtdHP31TA==,iv:xtcruWNtxDTjV5yBh4zL42tHAUo8/kLevOyo0dIlKX8=,tag:yh9SCcv7Xvmmj141ZnOkDA==,type:str]
    namespace: ENC[AES256_GCM,data:dlW6sdyc,iv:afSg2j9FD7JG0o3mGFj6PAlwq/DyQVt/Cew4GGnUL1Y=,tag:zsqoV1q2Lv3tReOYNXxAsQ==,type:str]
type: ENC[AES256_GCM,data:MnjZT/U4,iv:Ehar+gKQHe+CJO/jaOBM9eYG1DrAX1gZkG971Xi+mZw=,tag:c0AaCLHop7dwzE1BH1kkNw==,type:str]
stringData:
    email: ENC[AES256_GCM,data:b8ah8MD07YFgB8/JreU=,iv:zivlQrlfD3+0SV2bgS56TioCTS5ar4IZ9QTipZDpPGk=,tag:IQr0VKgusKvdBIfVegW6zQ==,type:str]
    password: ENC[AES256_GCM,data:1dn502UQ,iv:lbLNlnatK+herhEvqkktfkkFgO/TiSHUkinqtn+2O7E=,tag:KVuJVOvEfBdN6qBUF1Cu6w==,type:str]
    name: ENC[AES256_GCM,data:B4w=,iv:iqR0Njx92JCJB86Y/kPLw7Kt79nCxSj+1h51tGa2uBA=,tag:L9Yk1xkrCDPFkTERZcDbAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb05HUiswcEF3Mm1UbDZr
            WDg5bk9tU0ZGZHBBN2R0cjZkS2dsaHNPZGtjCjEwWjJ1RzJjOXh0SGxUa09kVERw
            dnhCbHFBTTNGUjR1UkxzUjBkNWZKWTAKLS0tIFNRbTFzcUJIUXFiZEdlc2FwVWhP
            ajAveGZ0bHhEMkdzdVVZZFBaZ3l2TVEKByKFLeNR8reTNii7vNiWjXe4e5LuTGIE
            UX5DUXXJN/CQM2dqFbVjMsOKearxv7qxESqPPh8+jYKQT9Sl1yDInQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:47:46Z"
    mac: ENC[AES256_GCM,data:mpbOMjjma/8npwZTpDS3lRCMpaSLE5ftekWz7ZMNCiLyf55c4StZ65FSadnSBuWXfNR3tD4vfDnB8hKvSD40QiUO3p4iX/mvzQhjnBiW8oXoTHMfjWHQd4qu0PZRrVmVMXy0XGCuxeEV1Vsct6ZQx4NdoNkI7ck5F09Au7kpCcI=,iv:l50MNwpSDeZtSbBbvyhS5PS5umX8Fx+H6o84EDT4q1c=,tag:gAhMY8YBBWkn/r1oKQagNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
