apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-sync.yaml
  - gotk-components.yaml
patches:
  - patch: |
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      spec:
        ref:
          branch: ${branch}
    target:
      kind: GitRepository
      name: "flux-system"
