apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-tenant
  namespace: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: tenant
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 10m
  values:
    tenant:
      name: loki
      configSecret:
        name: env-config
        existingSecret: true
      pools:
        - name: data
          servers: 1
          volumesPerServer: 1
          size: 100Gi
          storageClassName: delete
      poolsMetadata:
        annotations:
          k8s.grafana.com/scrape: "true"
      buckets:
        - name: loki-admin
        - name: loki-chunks
        - name: loki-ruler
      certificate:
        requestAutoCert: false
      metrics:
        enabled: true