apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: vector
      version: "0.43.0"
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      interval: 10m
  values:
    role: Agent
    resources:
      requests:
        cpu: 500m
        memory: 64Mi
      limits:
        cpu: 6000m
        memory: 1024Mi
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    customConfig:
      data_dir: "/vector-data-dir"
      sources:
        kubernetes:
          type: kubernetes_logs
      sinks:
        # stdout:
        #   type: console
        #   inputs: [kubernetes]
        #   encoding:
        #     codec: json
        loki:
          type: loki
          inputs: [kubernetes]
          endpoint: http://loki-gateway.loki.svc.cluster.local
          encoding:
            codec: json
          labels:
            source_type: "{{ source_type }}"
            stream: "{{ stream }}"
            container_id: "{{ kubernetes.container_id }}"
            container_image: "{{ kubernetes.container_image }}"
            container_image_id: "{{ kubernetes.container_image_id }}"
            container_name: "{{ kubernetes.container_name }}"
            pod_ip: "{{ kubernetes.pod_ip }}"
            pod_name: "{{ kubernetes.pod_name }}"
            pod_namespace: "{{ kubernetes.pod_namespace }}"
            pod_node_name: "{{ kubernetes.pod_node_name }}"
            pod_owner: "{{ kubernetes.pod_owner }}"
            pod_uid: "{{ kubernetes.pod_uid }}"
            message: "{{ message }}"

