apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: vector
      version: "0.43.0"
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      interval: 10m
  values:
    role: Agent
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    customConfig:
      data_dir: "/vector-data-dir"
      sources:
        kubernetes:
          type: kubernetes_logs
      sinks:
        # stdout:
        #   type: console
        #   inputs: [kubernetes]
        #   encoding:
        #     codec: json
        loki:
          type: loki
          inputs: [kubernetes]
          # endpoint: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
          endpoint: http://loki-gateway.loki.svc.cluster.local
          encoding:
            codec: json
          labels:
            job: vector
    # customConfig:
    #   sources:
    #     kubernetes_logs:
    #       type: "kubernetes_logs"
    #       include:
    #         - namespaces: ["kube-system"]
    #   sinks:
    #     loki:
    #       type: loki
    #       inputs:
    #         - kubernetes_logs
    #       endpoint: http://loki-gateway.loki.svc.cluster.local
    #       encoding: json
    #   transforms:
    #     - type: "log_to_json"
    #       inputs:
    #         - kubernetes_logs
    #   # https://github.com/vectordotdev/vector/issues/3057