apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: vector
      version: "0.43.0"
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      interval: 10m
  values:
    role: Agent
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    customConfig:
      sources:
        type: "kubernetes_logs"
      sinks:
        loki:
          type: loki
          inputs: ["kubernetes_logs"]
          endpoint: http://loki-gateway.loki.svc.cluster.local
          healthcheck: true
          encoding.codec: "json"
# https://github.com/vectordotdev/vector/issues/3057