apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  interval: 10m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.1"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      interval: 10m
  # TODO: maybe use the existingConfigSecret
  valuesFrom:
    - kind: Secret
      name: democratic-csi-connection
      valuesKey: host
      targetPath: driver.config.sshConnection.host
    - kind: Secret
      name: democratic-csi-connection
      valuesKey: username
      targetPath: driver.config.sshConnection.username
    - kind: Secret
      name: democratic-csi-connection
      valuesKey: port
      targetPath: driver.config.sshConnection.port
    - kind: Secret
      name: democratic-csi-connection
      valuesKey: privateKey
      targetPath: driver.config.sshConnection.privateKey
    - kind: Secret
      name: democratic-csi-connection
      valuesKey: shareHost
      targetPath: driver.config.nfs.shareHost
  values:
    csiDriver:
      name: org.democratic-csi.nfs
    driver:
      config:
        driver: zfs-generic-nfs
        nfs:
          mountCommand: /bin/mount
          unmountCommand: /bin/umount
          shareStrategy: setDatasetProperties
        zfs:
          datasetParentName: zdata/k8s/volumes
          detachedSnapshotsDatasetParentName: zdata/k8s/snapshots # https://github.com/democratic-csi/democratic-csi/blob/3974268272a84e9c22c47cae2fca847a8d422bad/examples/zfs-generic-nfs.yaml#L37
          datasetPermissionsMode: "0777"
          # datasetPermissionsUser: 65534
          # datasetPermissionsGroup: 65534
          cli:
            sudoEnabled: true
            paths:
              sudo: /usr/local/bin/doas
