apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-democratic-csi
spec:
  description: allow democratic-csi to nfs server and kube-apiserver
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: democratic-csi
      k8s:io.kubernetes.pod.namespace: kube-system
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
