apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beyla
  namespace: lgtm
spec:
  interval: 10m
  chart:
    spec:
      chart: beyla
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
