nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: HelmRelease
        path: spec/values/grafana/dashboardsConfigMaps/cilium
      - kind: HelmRelease
        path: spec/values/grafana/dashboardsConfigMaps/pfsense
