apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lgtm
resources:
  - namespace.yaml
  - helm-repos.yaml
  - minio-tenant.yaml
  - lgtm-distributed.yaml

patches:
  - target:
      kind: HelmRelease
      name: lgtm-distributed
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: lgtm
