apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-distributed
  namespace: lgtm
spec:
  interval: 10m
  chart:
    spec:
      chart: lgtm-distributed
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    grafana:
      enabled: true
      grafana.ini:
        analytics:
          check_for_updates: false
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Loki
              access: proxy
              type: loki
              isDefault: false
              jsonData:
                httHeaderName1: X-Scope-OrgID
              secureJsonData:
                httpHeaderValue1: 1
              orgId: 1
              url: http://lgtm-distributed-loki-gateway.lgtm.svc.cluster.local/
    loki:
      enabled: true
      analytics:
        reporting_enabled: false
        usage_stats_url: ""
      compactor:
        extraArgs:
          - -reporting.enabled=0
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          accessKeyId: ${accessKeyId}
          secretAccessKey: ${secretAccessKey}
          endpoint: ${endpoint}
          insecure: true
          s3ForcePathStyle: true
      storageConfig:
        tsdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          object_store: s3
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: true
    mimir:
      enabled: false
    tempo:
      enabled: false
    grafana-oncall:
      enabled: false
