apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-distributed
  namespace: lgtm
spec:
  interval: 10m
  chart:
    spec:
      chart: lgtm-distributed
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    grafana:
      enabled: true
    loki:
      enabled: true
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
    mimir:
      enabled: true
    tempo:
      enabled: true
    grafana-oncall:
      enabled: false
