apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki-minio-console
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - lgtm-minio.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: lgtm-minio-console
          port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - grafana.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: lgtm-distributed-grafana
          port: 80
