apiVersion: ENC[AES256_GCM,data:0Rw=,iv:Y0D+Ot42bOyufuPnRLY7N2U9Z7UxMLBhVHVp82NRGQE=,tag:v7sb1CewDNG1dX5XjcebZQ==,type:str]
kind: ENC[AES256_GCM,data:d2Cy9+Mc,iv:lbriUyhPozT466XvcwDiZQAj9j/xC+8U7ujiT3g2t80=,tag:aQLq1sXoFF5LmlTcL1VafA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h6zO23uV9GLtOWYEaA==,iv:Be3J5W/eW+DkjBPkcxWFHaYm3s+LUrQ2pTQxFniy00g=,tag:+1ipwsnD6iO78iC8B0FgVA==,type:str]
    namespace: ENC[AES256_GCM,data:UmVmPm1AHZ0ZiWgvin3+kQ==,iv:byF3TAr79b7z/616TrsATWb6Cyg1PBZdPGMMx79SWqg=,tag:HLwuaC1isY9aJTS97mRjWg==,type:str]
type: ENC[AES256_GCM,data:eYRpYqvj,iv:iyCPcIkVOaRkqDzXsXtPqUVmR3WHYbZgdwaIAYH1ce0=,tag:le8i2JnA44OwRXqRyWP47g==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:+ynTsyo=,iv:bwktGlxmZ+mUGuQUDgSOTjrKmlgVKnG6NPZnR/nUXUs=,tag:NumNOZcpBfoQFweIu2F/QA==,type:str]
    admin-password: ENC[AES256_GCM,data:FuzApPM8dPZDPQ==,iv:l37/j3F09PoycacE+RWxPOijLhpiBJriSxbTCf0v47c=,tag:uXTu9ZPf5zWok94BJSKJEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVVdNNTB1YzRPZGdvUXpZ
            OThaRTcyTHNLZU16UnFIVVdhRTdmWmxSbHkwCmtTS2M2MU13elN5UWtxbDlOdno1
            N1kwanBzNkxWK2ltWWJBRVJVczVyakEKLS0tIE0wOEVqOXpmWWFKUld5SklBdXZP
            SlhGSXoyY0hkdGpDbkFPdkhZaEZZdHcKRlatUIivDAyFwsqcGjaiDysKwfNbQS7D
            IaS5WGzh7Rwn6kMT0UuOHF6JzwT9qZIof0u86z/19UIeMOiR4RG5fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-06-10T10:00:21Z"
    mac: ENC[AES256_GCM,data:R+S4aSbhSDV1oJt3mAPs2r3GbG+Xmrg60mMEhleW2kw93bY+XJxi8QL9if2DP0hkwa00I1Oj0G1NsJQLW8xLRxzKAooAadueYEc+1cDsaR8rSLXjXsvExzPr+W5iqveH2N9em71mZJwFIRElvBnvw1oeB6hmlLVXA83EmhYO8N4=,iv:0Jf9KPz91X+VXH8kQHIgwo7FJIS84K7z9A3JQmD5ie0=,tag:HNijx6wUPVa4rjkQy4xs9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
