apiVersion: ENC[AES256_GCM,data:0Rw=,iv:Y0D+Ot42bOyufuPnRLY7N2U9Z7UxMLBhVHVp82NRGQE=,tag:v7sb1CewDNG1dX5XjcebZQ==,type:str]
kind: ENC[AES256_GCM,data:d2Cy9+Mc,iv:lbriUyhPozT466XvcwDiZQAj9j/xC+8U7ujiT3g2t80=,tag:aQLq1sXoFF5LmlTcL1VafA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h6zO23uV9GLtOWYEaA==,iv:Be3J5W/eW+DkjBPkcxWFHaYm3s+LUrQ2pTQxFniy00g=,tag:+1ipwsnD6iO78iC8B0FgVA==,type:str]
    namespace: ENC[AES256_GCM,data:UmVmPm1AHZ0ZiWgvin3+kQ==,iv:byF3TAr79b7z/616TrsATWb6Cyg1PBZdPGMMx79SWqg=,tag:HLwuaC1isY9aJTS97mRjWg==,type:str]
type: ENC[AES256_GCM,data:eYRpYqvj,iv:iyCPcIkVOaRkqDzXsXtPqUVmR3WHYbZgdwaIAYH1ce0=,tag:le8i2JnA44OwRXqRyWP47g==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:+ynTsyo=,iv:bwktGlxmZ+mUGuQUDgSOTjrKmlgVKnG6NPZnR/nUXUs=,tag:NumNOZcpBfoQFweIu2F/QA==,type:str]
    admin-password: ENC[AES256_GCM,data:K3VVvBs=,iv:NW27wD/EWrsF4cl+88K/uIYULGLHOssnpWtlNCY3pTw=,tag:XAmVarCTTCj7GiJwsxpVuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVVdNNTB1YzRPZGdvUXpZ
            OThaRTcyTHNLZU16UnFIVVdhRTdmWmxSbHkwCmtTS2M2MU13elN5UWtxbDlOdno1
            N1kwanBzNkxWK2ltWWJBRVJVczVyakEKLS0tIE0wOEVqOXpmWWFKUld5SklBdXZP
            SlhGSXoyY0hkdGpDbkFPdkhZaEZZdHcKRlatUIivDAyFwsqcGjaiDysKwfNbQS7D
            IaS5WGzh7Rwn6kMT0UuOHF6JzwT9qZIof0u86z/19UIeMOiR4RG5fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T12:05:04Z"
    mac: ENC[AES256_GCM,data:FwSfSwDo4gpSD2ZdBDsdoauU+GZ0j5822DsmlZX4YcA77j5jxo2IDk3C9q/LJXru/B228YbNtuCewQuMLkOCU6FfL4AIat3t3S8uVJbugqjvpy18aPg1/etq5FL/K+35dpBh4JqE71B0to+IxY5Ja/DnN1N/BHVjyCFsNTf2Xl0=,iv:3AnIvzMTxisof8bJcgWUIJLLCsNXULcz7QqEoMKaS/k=,tag:SpU2KT00ICFQUPky59Yi9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
