apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coroot-ce
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: coroot-ce
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: coroot
      interval: 10m
  values:
    clickhouse:
      shards: 2
      replicas: 2
