apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coroot
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - coroot.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: coroot-ce-coroot
          port: 8080
