apiVersion: ENC[AES256_GCM,data:3RI=,iv:pnvQ+HIEnAhVzZEk/NsuQPrxEcZD4vCWL8OGtd6IQqI=,tag:LRyYCdI6Zd9QcgTVthBZLw==,type:str]
kind: ENC[AES256_GCM,data:RRILq6OB,iv:OcBVbM0Hq5+XFvNbYgPUTjQzrZI/x+5mBW9zO/nDN/s=,tag:S26n7NyyvXoTLlQYL028yA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AXMcs/z/YxRvTWfUUXx/cw==,iv:hfOGGSnZ4br/x1YlVC2SWP0Gaxc2zAlLRHQkXc35uOg=,tag:PSd9zSbzaf9SQ59+VGeCKw==,type:str]
    namespace: ENC[AES256_GCM,data:Oau+tnQgbMzMbkQ=,iv:x3/AGKooBgQp7g42fDcr7UypTOjoImgYhCq/97kZMmg=,tag:0rjrWE0OnGbNL+1u4WQ5kw==,type:str]
type: ENC[AES256_GCM,data:tccWJumW,iv:x8gm8BtV0kBZWCbh4wpW9mEjbG+8SjnXoJmJ1UincFQ=,tag:RsmawgwlrPZ1iqiYS3Hj7g==,type:str]
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:aG7bRMljzBUstPE=,iv:CJRWA++tMHHw0ST/7AtnfM2emDlbqrmKXaDAFkDBtfo=,tag:240unW36Yx+Ur41We4vlZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZjJLSi9WNDA2TDBxbngr
            OW1XaStFNllaZS9qUGFrNUsyblE3WjRFU1VnCjI3SW5US1dROFRQdjRRS1JRUWgx
            S29PSlNyMGpIUTZveVFqRXorUERWNjAKLS0tIEtXQzN2VnFsRU9Ld1ptUi9ZL2JD
            Z0pEQ3QrOFAwWHZNUElBNHNOU05GMWcKra/WpDigAoewBW7hCB4VN+hlnPnE1rp1
            zEFFuaqqmdGnsFMYEudsVI6UlEsINffbw2iUtpDY2EFThgXht89sTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:47:30Z"
    mac: ENC[AES256_GCM,data:B8jXe1OkaMKwA1F0BPoBwaAccfEgemPK1n0qWLR50fE6+e6yo4G/J8BSXSGpDbK4W2S7K66NJAqzYjmFG1NLhpJcrw1+oAomXoP64swVkovzb2rz+yw32grmWEuqi+qH1fv2z11l4O3LqNOP6xJWuKr6XBg8w0c7k4SOxHFJnJ0=,iv:5y8QOiHRN5Oh/e4ryPv+CsEF9uLv3lKbyyOzQNIcfBQ=,tag:oq65aYZi/PKkjyaxcMiAaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:RPw=,iv:ONOnwyHEA+0VaxsIns5NgAZ4e/BvAfvrgn8DUx6ecN4=,tag:rLKCuj1b6UDPwDfeYviQaA==,type:str]
kind: ENC[AES256_GCM,data:b9W19x99,iv:50lACUAVQkb9f+2Uelm5TmKAAF0hC+OoJXlLLbZSSsw=,tag:BHDc9tskqwZXO6pAi83TBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5+CYI2rZOMCyfogFohxvbPt3VBib8TM=,iv:jdlciArrgVk85vLcUnMMT3t2kYDEd9nuxNQ8khGUOk4=,tag:SCPSgZSHHAHLs8Q/Cfoukg==,type:str]
    namespace: ENC[AES256_GCM,data:QW6wa9Z4dCACy8s=,iv:j5gdXbNpZkDIDiQFuC+aZVLN1Ky6stlyxpWhW3/Q/MY=,tag:aWCufPbxTp2mwXu0lCtrkA==,type:str]
type: ENC[AES256_GCM,data:+8kVYE+k,iv:outUuPsG4PsP6cbCqPMaR5aFmI1xRAETdVkKukSz98E=,tag:HawvLKjJhWlM69AzOuEB1Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:X24TmqtV,iv:Qi8czuBjZtVdPxjS/+g+imw8FhDYrAzG8FsQNKjmrQY=,tag:DUnI3CT9njVp2U1/ep8ICg==,type:str]
    password: ENC[AES256_GCM,data:EOpVhR6Z,iv:lwK1wb0NpiG6SuSu+gmx7bN9wy8N9SOcrJnEfQoeZ24=,tag:X9I98q4gQ2B2NRQbjrRjmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZjJLSi9WNDA2TDBxbngr
            OW1XaStFNllaZS9qUGFrNUsyblE3WjRFU1VnCjI3SW5US1dROFRQdjRRS1JRUWgx
            S29PSlNyMGpIUTZveVFqRXorUERWNjAKLS0tIEtXQzN2VnFsRU9Ld1ptUi9ZL2JD
            Z0pEQ3QrOFAwWHZNUElBNHNOU05GMWcKra/WpDigAoewBW7hCB4VN+hlnPnE1rp1
            zEFFuaqqmdGnsFMYEudsVI6UlEsINffbw2iUtpDY2EFThgXht89sTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:47:30Z"
    mac: ENC[AES256_GCM,data:B8jXe1OkaMKwA1F0BPoBwaAccfEgemPK1n0qWLR50fE6+e6yo4G/J8BSXSGpDbK4W2S7K66NJAqzYjmFG1NLhpJcrw1+oAomXoP64swVkovzb2rz+yw32grmWEuqi+qH1fv2z11l4O3LqNOP6xJWuKr6XBg8w0c7k4SOxHFJnJ0=,iv:5y8QOiHRN5Oh/e4ryPv+CsEF9uLv3lKbyyOzQNIcfBQ=,tag:oq65aYZi/PKkjyaxcMiAaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
