apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustfs
resources:
  - namespace.yaml
  - helm-repos.yaml
  - rustfs.yaml

patches:
  - target:
      kind: HelmRelease
      name: rustfs
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: rustfs
