apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
resources:
  - namespace.yaml
  - helm-repos.yaml
  - cloudnative-pg.yaml

patches:
  - target:
      kind: HelmRelease
      name: cloudnative-pg
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: cloudnative-pg
