apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - helm-repos.yaml
  - minio.yaml

patches:
  - target:
      kind: HelmRelease
      name: minio-operator
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: minio
