apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: operator
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
      interval: 10m
