apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: observability
  namespace: minio
  labels:
    app: observability
spec:
  users:
    - name: storage-user
  configuration:
    name: storage-configuration
  pools:
    - servers: 4
      name: pool-0
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault