apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  - namespace.yaml
  - network-policies.yaml
  - victoria-metrics-k8s-stack.yaml
  - victoria-logs-agent.yaml
  - victoria-logs.yaml
  - routes.yaml
  - scrape-configs.yaml

patches:
  - target:
      kind: HelmRelease
      name: victoria-metrics-k8s-stack
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: victoria-metrics-operator
