apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: hubble
spec:
  selector:
    matchLabels:
      k8s-app: hubble
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: hubble-metrics
      path: /metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: immich-db
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immich-db
  namespaceSelector:
    matchNames:
      - immich
  podMetricsEndpoints:
    - port: metrics
      path: /metrics

