apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.72.5"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 10m
  values:
    fullnameOverride: vm-stack
    victoria-metrics-operator:
      crds:
        cleanup:
          enabled: true
          image:
            tag: "v1.35.2" # TODO: update to k8s when image is available
    vmsingle:
      enabled: true
      spec:
        storage:
          storageClassName: zfs-observability
          resources:
            requests:
              storage: 50Gi
    vlogs:
      enabled: true
      spec:
        retentionPeriod: "30d"
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: zfs-observability
              resources:
                requests:
                  storage: 100Gi
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    grafana:
      enabled: true
      persistence:
        enabled: true
        type: pvc
        size: 5Gi
        storageClassName: zfs-observability
      admin:
        existingSecret: grafana-admin
