apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.79.0"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 10m
  values:
    fullnameOverride: vm-stack
    vmsingle:
      enabled: true
      spec:
        # securityContext:
        #   fsGroup: 65534
        #   runAsUser: 65534
        #   runAsNonRoot: true
        storage:
          storageClassName: delete
          resources:
            requests:
              storage: 50Gi
    vlogs:
      enabled: true
      spec:
        retentionPeriod: "30d"
        # securityContext:
        #   fsGroup: 65534
        #   runAsUser: 65534
        #   runAsNonRoot: true
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: delete
              resources:
                requests:
                  storage: 100Gi
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    grafana:
      enabled: true
      initChownData:
        enabled: false
      podSecurityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      containerSecurityContext:
        runAsUser: 65534
        runAsGroup: 65534
      persistence:
        enabled: true
        type: pvc
        size: 5Gi
        storageClassName: delete
      admin:
        existingSecret: grafana-admin
      plugins:
        - victoriametrics-logs-datasource
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: VictoriaLogs
              type: victoriametrics-logs-datasource
              access: proxy
              url: http://victorialogs:9428
              isDefault: false
