apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.78.0"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 10m
  values:
    fullnameOverride: vm-stack
    # victoria-metrics-operator:
    #   crds:
    #     cleanup:
    #       enabled: true
    #       image:
    #         tag: "v1.35.2" # TODO: update to k8s when image is available
    vmsingle:
      enabled: true
      spec:
        storage:
          storageClassName: delete
          resources:
            requests:
              storage: 50Gi
    vlogs:
      enabled: true
      spec:
        retentionPeriod: "30d"
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: delete
              resources:
                requests:
                  storage: 100Gi
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    grafana:
      enabled: true
      initChownData:
        enabled: false
      podSecurityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      containerSecurityContext:
        runAsUser: 65534
        runAsGroup: 65534
      persistence:
        enabled: true
        type: pvc
        size: 5Gi
        storageClassName: delete
      admin:
        existingSecret: grafana-admin
