apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
data:
  config.yaml: |-
    server:
      database: "/data/database.db"
      sources:
        - path: "/data"
          name: data
          config:
            defaultEnabled: false
            createUserDir: true
