apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: docker.io/gtstef/filebrowser:latest
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: filebrowser-data
              mountPath: "/data"
      volumes:
        - name: filebrowser-data
          persistentVolumeClaim:
            claimName: filebrowser-data
