apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway
  hostnames:
    - filebrowser.kubernetes.home
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: filebrowser-service
          port: 80
