apiVersion: ENC[AES256_GCM,data:gsc=,iv:8MICSCWdcMTr9poU+6fBtA9+jBtnVJvTkF+Qit/eP8M=,tag:PTiJhYNYZl8shiGhMzqnGQ==,type:str]
kind: ENC[AES256_GCM,data:uZDdJVg6,iv:Huohr3rfqyrpkGyobExiuQEqi/89cLaQE9xSMzuKLVo=,tag:rREbqRUam1YHPQKhtg9SgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:T3Wp5iW8UPoRKKsqhw==,iv:u6yisL9vrsVwGeubcM3qgp8HJxMPpo7VH6TtCBCjW/E=,tag:GR8wjGvWgNC1Om6H8ux2+A==,type:str]
    namespace: ENC[AES256_GCM,data:J8ZHPxHx5goucTVQkCJU3w==,iv:34d5IkyYi3qAkCcVxkP6HtiuHWn/lNE4Y0vutrd3rQ4=,tag:shcGd2LTxYW6iZa51qlozQ==,type:str]
type: ENC[AES256_GCM,data:cFOzbLlV,iv:txqRldeD98NbhxQyG6gsRjh08bqJqQ/tnZBg0+/8TLI=,tag:81XSR/E5Q/SRhxW+u7Ec0w==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:L3qrEjk=,iv:RcOtRnxNzS8yqDRhM2CpB1W6zWBs6Tm6LmL7YpiSEPQ=,tag:GsfAhh8/B7cTxPa6GGVEQg==,type:str]
    admin-password: ENC[AES256_GCM,data:rlgE5rs=,iv:0TSv7fs/DUHizem5/bGwyqbGr//DnUyTZbWhYYFFBDo=,tag:R2KGDn3jN3pZsVbo5ugiNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFR6Y1R5bEZS
            MWRFUWVKbFRiUm5pZCtRdFcyemh5cW5Tb3ZiMmNteGcwVlYwZUZLakxlbnVQdE9L
            WkxjWjNCdURCYXhaQnR6UE9jK0d6V0NQYkNvcTdkOTRvMWx3WGdkckg4YnJ2eWxo
            ODhsdWRDWlM5NTlYZzE2eTl1dnZ0cElPRFdaOTB2NHdWOFd0Y2RRUzBheWRkczZt
            bXV2T1V4YzRpZWVsWGp5N1IxZUVWUnpXeXlIb3FGK2JmWTRoVmFMR0dyR0U3aDNL
            ZHcxQ01ta0NxVll6Q3hRb0xlV1ErU1BuT0REUlZ0dzZNY0xoQ2hkMTlCU0FraDRs
            Q2ZoTmtsdDUzK2ErUittY3prazl6UUxuZmdUNnZndEZLRVUxWStZRUhQVkNDajNL
            UHludjhpZDdFaEZ3Z1VwY0hsV21XUkNRM0tXVU4rWll2eGZCTlA4cEIvNjRqQTRz
            ZlEyN05jS000aHpCaVQrdWVSbDNqNUdHTVBjdFhGeWxhVDNzcWF3aHdzM1Z6NHpJ
            SkxmSmdXd3hYWm56aVduY1R1Sk9jV2xyaWQrZnVMRkFkOUMyM25TQzZxNjNkRDZx
            U3JlemZpOVBPb2hqaUJ5MXAxSXRpR1pydkc2bldJRUdqb3V2em9xREhDNlN2NEJI
            UldJWFJTcFN3QXhneTZ3cWdXaTNiamRBRndyS1BLbm9kSGlyUGh1Zm1zMG55UUtE
            RDAxYkhwOVdLeUo0NWgxbWdkWHJwcUJjSjJERWF3Q2paSUYwY2hGcTI3QlcvaW1k
            OEtXN1FmRDlOQktlcitFTlNMYlVNNmJsRldzazNLR3lmY2NscExibnhRV0xjQUNQ
            WUNwTmJzTEZvQVNJZDhrVTNPSzRzdW9hRzB5RitUZ0lEQUZYVHk2V2JoWG8zMlIr
            NGpGdTRIYmNkaVhMeFh4OFhZZmFQZ1NUamNZYW8wbWFBaks0R1B5Uk1ZRnpSaUJj
            WXJROTJiQnZLU0RDZlhRUXpaRWp5dzRaOHFMTlppd1h2Tlh0WDRleG9HSGhkOW5k
            anJKYUdkajlqYTlHU0FPVnl4T2xMc1NOYnRTTlVWc1FLWjVtTTlKVG16eEJFRUlk
            dVk0UmlLSWNucmVSRk96dGIweS9qU2tJMW9rRkpCQWJMR1lhTjMvSUdyb2NxS21t
            elcrcjV2TnJRUmRiK09GQWlWRGJPcTdnK0ZTSEhyUTFGM2dPVmp6dGM3NlFRRmZn
            eW15Wi9wbzZJK1JjenFNQk1CWFpOZWIyMUxwV2Y2WjNTWlBoU1djeDl5YUY3aXZX
            cDNnL0xNenJVY2tHYzRPajZxM1BRWUdabDkxMHROT042bkF1Mm5iTmhHeWVvUit1
            cHhXVFAxTm0zWEtqZTdPdEFod3hrS2ViKzE0TVpYNndBTllTNjNQMVRkMUc0bGc3
            dndHRmZZZWdHMEdPK3E5VkJ6MmRqVjFDTTZITkJvdUNYOUFJV21hWXlRWXlhTVp6
            S0dLN3h2MTBMTHlpcm82T3lYV1hqUU52R1RoYXRITVczM0Fieis5YkJQQXVuQ0xK
            T21LV2VPQ0pzMlBQbmNrdkpXMVE3eVordG9PbVRtZ0crMS8zOStqYXlhaCtOTzI2
            bHBXTjFabEpXVXUyUG51ajFoSjNUb3phc1k0ODBXcDdTcjdpOXJqRkxCV1FmMGVH
            cDRPODQyVDF2Q3o0dlE5RnlHUUpSV0lwSVh3NnhFczdNa2dnelZhck1sRUk2YjlD
            TGpKdlNCdVZpVkgxa2Q4anE3UnZLZW91Q2N6c0IzQWx5WFNiNUw1QTR6OHpmdWU2
            eVVYUUM3eFFPRUJVcnNIUWVEUWludzA4b0hRZnlhYlVyUkhPdmtrM2gyQjRlQjZm
            aU9UMnRxWEJEU1lvelJOMzh4d0NuczVhYUcyUEZTb1JiVVZxYWZ4Nnoza205dGpD
            dG93L1Z5SDcySWY1bmpldWVYSm1mVVFUL2JJdU9WNjkrL2lZTGJ2ZWU0Y3FBZwpl
            cTRRUWtVNzdBU1g3ekZVcWdZcVBYTkQ5bW1xSHkvb0p1dHJzd0tjdHU0Ci0tLSBL
            ODNGNVBqQk9GZnZORTZZM2licGg0UDVFVmFlYTNDSlB0aDBRZGdtTkhZCkquUwvy
            CNdwDH1UqKKRO0b8SqiSYeeoeBWMG8IhpGPxO+6ahOFcowmZldIklbI6lVEZinYN
            DP7NrO8vh6YWJtw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq12jjf3cmmw26g585z9duxqc24ggj99djgzjcnznhy760a8eddgcy29a2cdu529wefxe75z4x83r288ueuvauysdq6tzmkmafysc6edkctqcz5j037qqp7xkml7mgc73z24vdztxwl8v048nq2zgvkwhljwnc4f2etzrywmdre7ed80v72gxfqrd35xs3k7g2mvu5876ecdhyg4ypqw9qtpud0f63uqs4y4nxpqsdyhgqqspz72jdxnwzv0ku8hpe98nx60skv58fq793h9zvwezncgpa7afjfyh2cx8wf2x0ckg3q56ay692eszvff9kudy2c493kke7gsst6yug4uxx5hgk503k5q3z8rz20j3wtykrf5a7y00w7agals7q6cp2qrvxqk7dvq8wwzr8mlyegf8epcran8uxpy434kxvaevyuef346hg9066xtf725gn2wqyxufz5j37ckgrry463ckay0g5hc6apzzm4w8rtc7evrg4e96q66tpy5c558fxawnksjqrs32qxuweehfrged5g22qvk4c997a0xakr0m7tc8fgrvxh8qnc9eq6g9stt5850zx2g7al757w2as8py2hq762eed3d977sjh657fzn4qp5trjswsgnypqmjvzutqqxkx8ngtjyhnkn9w3h2c0muq0ttzeyzfg90sgfgetgjcrgdacutc8s9c45ywwzuwl3xmslcy90k2chz8tdtheq92lj9kat4w8agjky78syjfqkd0rj5vr79fylw68q32f4a565a3x6xg8cer5lzcq64segegh89rn0yqv4p39jhv90szhz5d4qwfa3v03w3j0nt9fkjm2fsmpfzp7ydu5rvrzws9598mjp2kkrj2sydf92jmdlgqr9vjcwta5yw9dlxguy63h9w4qarcrcn92yy6puyzywdg7vv398dvpkqpsfj05djruua6p0cgv9cw5r6ac5h8lckml9a6gluyhd23yjf3tvt47q2pm3a4llc3c8uatpav5gwzumsjlvu3a6g4f07mchac4ddj0u729k72wzmzu5uvrfekmej4vvwyrmqv24yzvv6kfkyne582kczck5gzks5z2mvfxgae6p2dsqqc9cx4va4sucpsugnce4fc40fpghua9uw6yzgpz5ljmyg5sxtrpavyg9y3ed704vuv0tfay65ph0wqc07yntx2sngukvxz264lyjarcumk2z0628cvwqjqguyjsm3a6xnvnzptpj8tj8dnzdv9av5wd326geywfh74t2t3ts735psnlm52ucrpv4mzg5csfgyrkkzruhtsed2h93yvk08x9jfs5e0rm8f9uvvv8fqglkfxq9rp07lxqehn8hckp33h38gch7hz3mw943pdvceg5p75zjawjfzyxx44jqpg8tlrjgauuvfde2srt95sp7za5suxq5677jsxcrv08asedyxd3fdurt9h5sse2nq9xceyushuy8j058u4lpnvrzxlt0qx9rra4h5gz8mpj4jtr7apz8txgh23nndc98l7kvmffy2e63qn22s94j3vh06tnnzzekgc3m54r2ac3n0xrxlkwqgnpa9sa7xvdd539hgxsygkvkg4sycpdphyvxkc5zlc2tscxpqzjrdnt8rpwxhc2yfns3uxrk9ar9qtjnan4f3ch7v34gzzchtsndd4aay33dvg8qu0mhw5q29h53qmykpal7gzpmmz5qdk6kvlf5uwkxy5gf4v68az6t4ct5qd999eeya2vv8jp5nlcx0s5cqhygcn2593tlhxp448hqw2dezfewan3hdtslqac7zhgn253d9jnfska8g7ls6rm7hhylc88vdumu9d24ux2etc5lw98ynswh8n98wtwn3syas50qhhx2zvekxrlpde9kq6xwn426nhf6kgqdr6lywk2e60yyqtv9gmn
    lastmodified: "2026-05-13T11:05:24Z"
    mac: ENC[AES256_GCM,data:hgZO2W2Md9g51MQxt12ewX2C5FxPUlMrhdfY9e+FPY9NMfkVuQAn4lWNl+s2RjeL13CWu7/SsJQu+cvBplRiuW/e5TVZIoGne8PjJkym2F8czngczWz6M0fRkmJ9eDSN4wRZPkqfBVldkDu5AFRSV02qpUn4y4MMBs7Q6hXmLn0=,iv:Dhm2jX8/3LAcSL0FnKV7O1pglBEgADd7pgZ85aeKncs=,tag:prNnJByfBPdRlVnZHQxDuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
