apiVersion: ENC[AES256_GCM,data:Ao0=,iv:bB4StZJmsYn2dyNOF1FHGXWLJeeUW88SH2pS9CLmfT8=,tag:iSkDW9TnEiGAZedVUyX1EQ==,type:str]
kind: ENC[AES256_GCM,data:gmqdIEto,iv:Ufc7236NtCE3aMDdleWfqMq5zgYdvCg3BGp22m+efMk=,tag:wannfetsZqZNj9pOMfA/WQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xxr1DmD/bUzHnbHh2g==,iv:i5drv9NFyIpB0LdfMVXCKXSMzV+BaAEM3JlsRwy7IrM=,tag:q8Xqc4lxfXLc+zuEN14GUg==,type:str]
    namespace: ENC[AES256_GCM,data:gwlK2tXkrCr/dCS5v3sQaA==,iv:takKLmEJugc1Mw8fdMJYiEO4nm7mg0DoObIddoip0lQ=,tag:8st6bGnkCVN4EwmfILoyrg==,type:str]
type: ENC[AES256_GCM,data:y3FuUKJh,iv:qiOYyCTwDcZMU8KJgmeFlRT0HCzLfs8+fPr9DuSwGX4=,tag:iISdsa9WRtOVRDmDilrBMg==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:aZ9WZM0=,iv:fahNKfRPEZtBdxNoaEgqI19IFHTDy3p7trboidmuKv0=,tag:TUpo/oGrqDc7BzNKBskhzw==,type:str]
    admin-password: ENC[AES256_GCM,data:6E/tYK8h4r92Fw==,iv:BhIljE7gkLNFCGd0as4m4gU1TtCYfv6jI8Lc+AdO1Os=,tag:KxQ8x40oap/ic6Joy5ypFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMXNVYnlMb1NabXYwSWt2
            REx2OFl4NmNySFpzU09aaUVmc0NNL081d2dFCm53bDlUNzEzY0I0RmJUSC81amJ0
            QkxjNHFNVi9RUkpabi9LREVqdldGMG8KLS0tIERLWDFlZ2RGdGc1TUFmU212Um4x
            aGZxZk1WeUpzZHprV2lpMEVkYXBVK00KmjsGCLjcH4mUj/hKtXxuV4RADJo/bF9e
            gSxsIFLjBpO9IltNSMBEar+oK5C9bfjKHlMHF1IDm30nnYeU+5/4ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-06-10T09:52:12Z"
    mac: ENC[AES256_GCM,data:+rwV2B+R16n/ksN/Wm1Mc9EkR5HLEHyU9FhdrqmJGXcH9wuTQNw2BRFnU5NqGHQzlAwJposqUnoakfVfcbG+3Sj24RPLHyn1U+syWVTTjpZ7Zzp5QVgPKIPnlUpdp2EAp9XE8n3ZwCrgRo5Oy3mofTIYhwFZorU8pdcHYQltg5U=,iv:W9QsbLavj6WOuTaCJYKgWI9HZIZUT1EAYR18hrL5N38=,tag:j+ADWvNshdEAuFB+ObVd2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
