apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vector
resources:
  - namespace.yaml
  - helm-repos.yaml
  - vector.yaml

patches:
  - target:
      kind: HelmRelease
      name: vector
    patch: |-
      - op: add
        path: "/spec/chart/spec/sourceRef/namespace"
        value: vector
