apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
spec:
  interval: 10m
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: vector
      version: "0.45.0"
      sourceRef:
        kind: HelmRepository
        name: vector
      interval: 10m
  values:
    role: Agent
    serviceHeadless:
      enabled: false
    service:
      enabled: false
    resources:
      requests:
        cpu: 500m
        memory: 64Mi
      limits:
        cpu: 6000m
        memory: 1024Mi
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    customConfig:
      data_dir: "/vector-data-dir"
      sources:
        kubernetes:
          type: kubernetes_logs
      sinks:
        # stdout:
        #   type: console
        #   inputs: [kubernetes]
        #   encoding:
        #     codec: json
        loki:
          type: loki
          inputs: [kubernetes]
          endpoint: http://loki-gateway.loki.svc.cluster.local
          encoding:
            codec: json
          labels:
            source_type: |-
              {{ print "{{ source_type }}" }}
            stream: |-
              {{ print "{{ stream }}" }}
            container_id: |-
              {{ print "{{ kubernetes.container_id }}" }}
            container_image: |-
              {{ print "{{ kubernetes.container_image }}" }}
            container_image_id: |-
              {{ print "{{ kubernetes.container_image_id }}" }}
            container_name: |-
              {{ print "{{ kubernetes.container_name }}" }}
            pod_ip: |-
              {{ print "{{ kubernetes.pod_ip }}" }}
            pod_name: |-
              {{ print "{{ kubernetes.pod_name }}" }}
            pod_namespace: |-
              {{ print "{{ kubernetes.pod_namespace }}" }}
            pod_node_name: |-
              {{ print "{{ kubernetes.pod_node_name }}" }}
            pod_owner: |-
              {{ print "{{ kubernetes.pod_owner }}" }}
            pod_uid: |-
              {{ print "{{ kubernetes.pod_uid }}" }}

