apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 10m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      interval: 10m
