apiVersion: ENC[AES256_GCM,data:mRw=,iv:oC5hvMgg87Gvr1nC2hDE7jCFEURTXfUCDcnuRouEJXM=,tag:7/MI+ZhbLVz9AQIl6T9g4A==,type:str]
kind: ENC[AES256_GCM,data:SiCLICTS,iv:brqD5sByd/N0w5DwzsHkmosbfe0OQlRSmlRm4N78aAs=,tag:jhJXnsAfSoMCsboRza5Jbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9hxbpBAXIZdGo88UmkW3ww==,iv:/lPHN8vpFKYnGkCI0Z7XZQBhMINScRe6trsIFhXr6DA=,tag:+Lg/abkwnFSbjaWN9kU91w==,type:str]
    namespace: ENC[AES256_GCM,data:eymyx5yKEj8+hcU=,iv:F4oOt7DmbQoy4H/e9Ea9H5CQcqactzu3unG616ZVyUE=,tag:5LqSXznRHUbgTuNv51qJGA==,type:str]
type: ENC[AES256_GCM,data:JxNrYHqy,iv:yy6TVuHeWbJ8Qxok2X1HxMknPkkZneSylWr8YCTd304=,tag:NYQmfAxOAwvOpe25FB9svg==,type:str]
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:aHcGWcWTgbS1Vqc=,iv:Z309grgt7745lMdROu1J5Fz0mD5PWaWY1t0HIrf7Jvw=,tag:2XMkffu1EPTQaipXBFLgIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZkJ5dzh3VURzcDE4VkU5
            dERFQ1BIbUtlSjJLeGdUeEE4MXIvVC83RDBFCkR5TTBTUFRiYmI0VGNMd21XVEIx
            ZnF1UE9wR29VcHlJV294N2RycFhlcWMKLS0tIFZ1VW1lbDNRUGlUeUdzYlRCUVgr
            QWNxUXN5dEVQdDMzSGEyVVZtaFcwbjgKZXLj6NyFgSrOUGvxd+1UlpjVI3OSQeOK
            zlE2ZsNt2/8F184QfRjGHObI3ZoSmcLRNJsjwEpsX8munk+Rvp0ZkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:46:36Z"
    mac: ENC[AES256_GCM,data:llqGflggLLdWz0xPp2oD4ErtESPpniG4sIt6G83V2PUJKBvTHe3sjOmMVD5LjtRNMTAIlkJ2zZ8tHzkEWiZ0n2InIMGB+633wFtOWt7jAc9efjuUgEEiXm7WabWvgYVJQLCHhdIYKmhjxvgOra8oUeYyBrHz/l9xnAbXoBO9OAM=,iv:14rK2KhnHu3856ZIccteQpo44dIwhpsNfwQg1cZs5RE=,tag:qZfVdo9TExbJriunBLp/9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:9pM=,iv:TMV2JlUUzj8Z4WKh8M/9Xuztw7U7Ii/Ub0AJkVzGZgw=,tag:V/Drk8ugAQpGyV8SW2Jvhw==,type:str]
kind: ENC[AES256_GCM,data:XBc6KFMC,iv:CoJCwcaq5CHn/J92VxAU5ZRvIJKXEzG9lkLwb3yUfik=,tag:pNfvwdYbThRX4GRys+0dxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qLoSxjSJoYPtbDzB84aRhg2OzjWgYEo=,iv:Q9Xf4goQWiyRY5zVm8feDvf+iW7Ds/CMM6RYDGX9UT4=,tag:0KMcp7AzEuj2e2Z4IhPGUA==,type:str]
    namespace: ENC[AES256_GCM,data:g2HOBpJ4TOuK5FM=,iv:UZIo+ElCa9muPZUKdoH7kZec2S0zj/QuL/ZgecrARJs=,tag:7gc+juq51Q3oVtLzhhG6cw==,type:str]
type: ENC[AES256_GCM,data:7oxc+Vn3,iv:1D3/BqHYrVpAXRihi5pyMvD0QhHH8FKMrwbusB1isic=,tag:82gQ7c+pTWUDNbLjVne7Zg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:vK5Matrv,iv:eJMm/oXA2MtXm5w7sPv6VPlPw7pvCIJhkZlD2bqteGo=,tag:/RNHmOm9EipyLEDigEv3fw==,type:str]
    password: ENC[AES256_GCM,data:cGTPX6a9,iv:apB08xb132JAIczHtAndPSnLpeN9V2Ym29qf3Vuv1jg=,tag:8baSQWSUSI4xSUwZS9xZNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZkJ5dzh3VURzcDE4VkU5
            dERFQ1BIbUtlSjJLeGdUeEE4MXIvVC83RDBFCkR5TTBTUFRiYmI0VGNMd21XVEIx
            ZnF1UE9wR29VcHlJV294N2RycFhlcWMKLS0tIFZ1VW1lbDNRUGlUeUdzYlRCUVgr
            QWNxUXN5dEVQdDMzSGEyVVZtaFcwbjgKZXLj6NyFgSrOUGvxd+1UlpjVI3OSQeOK
            zlE2ZsNt2/8F184QfRjGHObI3ZoSmcLRNJsjwEpsX8munk+Rvp0ZkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl6vp2atvdt5juw86afrhryf87ng8dtlad5j3eg35r0v52mg74kspjthft
    lastmodified: "2026-05-13T11:46:36Z"
    mac: ENC[AES256_GCM,data:llqGflggLLdWz0xPp2oD4ErtESPpniG4sIt6G83V2PUJKBvTHe3sjOmMVD5LjtRNMTAIlkJ2zZ8tHzkEWiZ0n2InIMGB+633wFtOWt7jAc9efjuUgEEiXm7WabWvgYVJQLCHhdIYKmhjxvgOra8oUeYyBrHz/l9xnAbXoBO9OAM=,iv:14rK2KhnHu3856ZIccteQpo44dIwhpsNfwQg1cZs5RE=,tag:qZfVdo9TExbJriunBLp/9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
