apiVersion: ENC[AES256_GCM,data:F9c=,iv:pSaf7RNPT5vTmZxQzlfFnJ/ogZugcee2Z5oTKBFu92I=,tag:UHYuXyVjzEA1mGq8cCWQ1w==,type:str]
kind: ENC[AES256_GCM,data:st9xB35I,iv:kTuXBNrw2HVc2BW7FQdb5OyEZeCFG0QUNS6sgiY5s4A=,tag:3yXOuDSNzFB0NibxSXIySg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BYZrtdYPFeidbDimHX7xDQ==,iv:jcoBxHPsCE9nZC+5zDIHXvRlaaB9PDm39GDKrSYM/Kk=,tag:OR7wzxl1Iv6yL/i03ItX3w==,type:str]
    namespace: ENC[AES256_GCM,data:iUiqkeksmgsZeCI=,iv:fBAHajhtq0VnZozUVtoxo/p7FL7v9rB+eJxcn8QvORc=,tag:MNkRDVJ2OPPdpcXSa1ER+w==,type:str]
type: ENC[AES256_GCM,data:HEjcn0A3,iv:Z9JvWvdpiZX4pm91+OA1Q43LB9xCA1hJ/ceqSQdpSv8=,tag:qWOb8mvg54E7+uEY2g+OCQ==,type:str]
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:zVptVmMlmW1/rEQ=,iv:sxP+qmvLB8cozJs64Hjej8Xn+VJBfWaE+5fBwTft+2Y=,tag:RhXbntrZYAH9fKPFyYmnvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBiUXg3bEQx
            eGhxQVZqZC93TDlJa2tJN1ZsQ1RqSm8weHRQRmtldWxnMkhMWSswSXM3RnlQUzRk
            NHBvMjVEZlM4K1FoOVN0bzVYemFJNSsvRWxUQ0JROXcyYzhGM2p6dUZrdk9ML3VB
            c3JTUVV1T0xRVnlWYTl5OTV6czU4aXViSzhtbklwSmhjM0UvcjZYaERTS3VIWHND
            NDNiNkUzczk3Nzhrdm8xMGdsN1IxYTRMV1BUNXBPcGRGanVEbnRydlZKenBDOVdh
            QnQ1YWVPV09LL3kvbFNOMTkxc0NncVBqMHNpV0RTVkJlUkErTTcwMktVanNXQ1pi
            ZnZ0cmo1NlJaMUFvY2dZWDA2MEJkZ1VibTkyM3htRmdDUWl5WXMyK3d4d2hjNTUx
            Qm5xQWVIQ1NXaXBTRnVjOUw1WWIvcko3MVBWSVl4cVN5RFRCeEttNksrUU9DOG5V
            ZUV5TDZSN1p0alhvRjhTanpHamZUZVdRbzRZc21PVDNhS2Iya0trNTF6SGl5dVpJ
            dERmNDltcldZRmZ6UzhkRFNPcjdGUGltaE43NUNwWXBSTGNnVm45alNVV250RVFl
            eVc3aHhCQ1ZJS2xVaHd1STRrT3RBVWROQ0lOcDBEVXE2NDhJUEpZVC81dlhsRWpE
            Sk1TSFdtWVBWZitJdi8vLzlQSll6aTNzNWJKWkZEdVRsUURCeVVkQ1hyMTRoRVo2
            N1FVY2s3Tk5XTXJPeHdScVNMeHV3ZmIvOExxQjF3SGJLTTVSUzF6MnNNbDZnb2Ex
            U21tUWZBbmpndCtXWjdPNndpZGxmZThJSGlNT2FJR2I4WFZQY1JzaXhlVndZUGdx
            dFgrUnZiVjQyZWdBWjRyWjBldi95SmVPYWpGajErbDdreStJNVRQd3VqV3pHZk1G
            dys2TVIzWWNyWnEvSW0rYWxYU1Qzdk93TFd5VU5jN25mb1RmZnE0RGNTRW1NNHNE
            N3FCR3diRGxCblMxM1FkT1RsSllldDh5NkF4ZFd4dEk1NE1lNDdRRm1POHpoTk1F
            b2dCUi9kZmlwWnQ3UFpsSS9FY3FFWVJoRjlxc2tmci9iNm5qUkR3TzRobkZodzZR
            dWIvVnp6am4vbDBITHRZSkhRR3E5clBUemtnQTc0VENGdks3dzRVU3hsMU44RHFC
            QTFyYTRxTWVYWWkyTjY5TytQaGVPVlp1VEFIUENjZGlNczlDUnNSS1RKeTZlNmZ2
            T0J6bmFrWktBVy96dUtwRklBNXNUamYyOFE3aFROTnlGaHl2aWlOdy9CdHQzUVds
            Uk9yNFNzOE1naDZXYjdpeDFUMXFxcTdaQjhVMEI2Rmx0KzZiUU1kaDIzVWY3VEtJ
            cDUwVVhKcXlVZlYvTDFNY2p4WVRBazBpWUcxY0dkOWYwRnk4VWUvdVBEN0ZkMEsv
            Wk9meUNTc1ZXd0F1d2FPTG9HaU83dHkrUWNEbCsvRlpUQmJsZ3B1cndoNnY2NGMy
            c3h1WVNxOWt3MElUQ2JKSjJrNzc2aHViWVFodWpnMVdua1BOcnRvNHMxazlPM0xr
            RTVwNkNtK0wzaFlVNS9YeHhpd3VtNGtGWkZDejdzQWpsUjh4Y1dYdUJxaGhlVDZD
            SmZYL0IvYldaWWFIamhHOG15ajVJeThoa05Sazl0b2xhLzJvRGx1Yk1OWlpQTkMr
            TVRqL3AyUER2cWtOcGFmd0hnT2cwVEd5Y2YzVytYQ1ZlVkVaWEZNcU1qMTNvOGZU
            THgxQWhUTEtUZ2UreTU3R1dGYWNMb0U5R3RlTy9Qd2RpQUdGOWdsNUJsaFZHNWlo
            TW9GenZYUDMvSlRLTWxKdVlhcXE3U1pibzhBREtXaW5ZUzVqUEI0YmsrZTZLV1gz
            ak5iRHNkcVFmb0czaWVwL1F1eVg3YXJSUzU1M3laSTRSRTZ6QzNjVk92dnJkY0Nu
            RXBEcktqM0RDWS9oTmRXRk1kRHAydE1xSWRMMFZ4KzAwMDk1QlhiWjhBOXFXdwpm
            K0VkSUJXQ1hNODJrWXBZa1VocnBLT0p6ZktPVnZsUkJUdU9vSWRNdnN3Ci0tLSB3
            NHhPNnJtOGZoUGlUZjdwMWwwempuT2VHVjJLay9DMDFiR0ZHd3AycHk4CrV0+mN+
            VgvLwd8DuxY6PTKz9DK7UAhb/szJ2rm8bTcX+lXWY35g92lest7GrXmYriZSK+XT
            zYblujWGJk9yXF0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq12jjf3cmmw26g585z9duxqc24ggj99djgzjcnznhy760a8eddgcy29a2cdu529wefxe75z4x83r288ueuvauysdq6tzmkmafysc6edkctqcz5j037qqp7xkml7mgc73z24vdztxwl8v048nq2zgvkwhljwnc4f2etzrywmdre7ed80v72gxfqrd35xs3k7g2mvu5876ecdhyg4ypqw9qtpud0f63uqs4y4nxpqsdyhgqqspz72jdxnwzv0ku8hpe98nx60skv58fq793h9zvwezncgpa7afjfyh2cx8wf2x0ckg3q56ay692eszvff9kudy2c493kke7gsst6yug4uxx5hgk503k5q3z8rz20j3wtykrf5a7y00w7agals7q6cp2qrvxqk7dvq8wwzr8mlyegf8epcran8uxpy434kxvaevyuef346hg9066xtf725gn2wqyxufz5j37ckgrry463ckay0g5hc6apzzm4w8rtc7evrg4e96q66tpy5c558fxawnksjqrs32qxuweehfrged5g22qvk4c997a0xakr0m7tc8fgrvxh8qnc9eq6g9stt5850zx2g7al757w2as8py2hq762eed3d977sjh657fzn4qp5trjswsgnypqmjvzutqqxkx8ngtjyhnkn9w3h2c0muq0ttzeyzfg90sgfgetgjcrgdacutc8s9c45ywwzuwl3xmslcy90k2chz8tdtheq92lj9kat4w8agjky78syjfqkd0rj5vr79fylw68q32f4a565a3x6xg8cer5lzcq64segegh89rn0yqv4p39jhv90szhz5d4qwfa3v03w3j0nt9fkjm2fsmpfzp7ydu5rvrzws9598mjp2kkrj2sydf92jmdlgqr9vjcwta5yw9dlxguy63h9w4qarcrcn92yy6puyzywdg7vv398dvpkqpsfj05djruua6p0cgv9cw5r6ac5h8lckml9a6gluyhd23yjf3tvt47q2pm3a4llc3c8uatpav5gwzumsjlvu3a6g4f07mchac4ddj0u729k72wzmzu5uvrfekmej4vvwyrmqv24yzvv6kfkyne582kczck5gzks5z2mvfxgae6p2dsqqc9cx4va4sucpsugnce4fc40fpghua9uw6yzgpz5ljmyg5sxtrpavyg9y3ed704vuv0tfay65ph0wqc07yntx2sngukvxz264lyjarcumk2z0628cvwqjqguyjsm3a6xnvnzptpj8tj8dnzdv9av5wd326geywfh74t2t3ts735psnlm52ucrpv4mzg5csfgyrkkzruhtsed2h93yvk08x9jfs5e0rm8f9uvvv8fqglkfxq9rp07lxqehn8hckp33h38gch7hz3mw943pdvceg5p75zjawjfzyxx44jqpg8tlrjgauuvfde2srt95sp7za5suxq5677jsxcrv08asedyxd3fdurt9h5sse2nq9xceyushuy8j058u4lpnvrzxlt0qx9rra4h5gz8mpj4jtr7apz8txgh23nndc98l7kvmffy2e63qn22s94j3vh06tnnzzekgc3m54r2ac3n0xrxlkwqgnpa9sa7xvdd539hgxsygkvkg4sycpdphyvxkc5zlc2tscxpqzjrdnt8rpwxhc2yfns3uxrk9ar9qtjnan4f3ch7v34gzzchtsndd4aay33dvg8qu0mhw5q29h53qmykpal7gzpmmz5qdk6kvlf5uwkxy5gf4v68az6t4ct5qd999eeya2vv8jp5nlcx0s5cqhygcn2593tlhxp448hqw2dezfewan3hdtslqac7zhgn253d9jnfska8g7ls6rm7hhylc88vdumu9d24ux2etc5lw98ynswh8n98wtwn3syas50qhhx2zvekxrlpde9kq6xwn426nhf6kgqdr6lywk2e60yyqtv9gmn
    lastmodified: "2026-05-13T10:46:56Z"
    mac: ENC[AES256_GCM,data:RBkpez9qxk78qO5m2jqy4ULZqge7AEIyz+wSbKDiJ623WGaKJrJK7TBipKxHYdNnKBA+/FeZ5vj1VxbJBQVAShDbm+6FQFnYBD9ddF7MD54BUiCLN9p+D1V3tSz2GGHl/tF5kIhoqSgkj11UtrO9zJzNGm1VWndj7p0NoADacbE=,iv:1tnJPWy4OAZY4UvkeeIrKw+doJY1G2zrUbrMRtugOvA=,tag:OzEmwxJTg6RnhLaZaD0wsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
